// src/main/webapp/react/service/AjaxService.js
import ApiConstants from '../constants/ApiConstants';
import Flight from '../entity/Flight';
import {ValidationResponse} from 'react-jsf';

export default class AjaxService {
  static URL = ApiConstants.BASE_URL + 'ajax/';

  /**
   *
   * @param {Flight} flight
   * @param {number} passengerCount
   * @return {Promise<ValidationResponse>}
   */
  static async validatePassengerCount(flight, passengerCount) {
    // do ajax call
    return new Promise((resolve, reject) => {
      $.get({
        url: AjaxService.URL + `${flight.id}/validatePassengerCount`,
        contentType: 'application/json',
        data: {
          passengerCount: passengerCount,
        },
        error: function(jqXHR, textStatus, errorThrown) {
          reject(errorThrown);
        },
        success: function(data) {
          let json = JSON.parse(data);
          resolve(new ValidationResponse(json.error, json.message));
        },
      });
    });
  }
}

// src/main/webapp/angular/app/services/AjaxService.ts
import ApiConstants from '../constants/ApiConstants';
import Flight from '../entity/Flight';
import ValidationResponse from '../entity/ValidationResponse';
import {Injectable} from '@angular/core';
import {HttpClient, HttpParams} from '@angular/common/http';

@Injectable()
export class AjaxService {
  static URL = ApiConstants.BASE_URL + 'ajax/';

  constructor(private http: HttpClient) {
  }

  /**
   *
   * @param {Flight} flight
   * @param {number} passengerCount
   * @return {Promise<ValidationResponse>}
   */
  async validatePassengerCount(
      flight: Flight, passengerCount: number): Promise<ValidationResponse> {

    const params = new HttpParams().set('passengerCount',
        passengerCount.toString());

    // do ajax call
    return this.http.get<ValidationResponse>(AjaxService.URL +
        `${flight.id}/validatePassengerCount`, {
      params: params,
    }).toPromise();
  }
}
