// src/main/webapp/resources/js/react/components/pages/FlightOverview.js
import React from 'react';
import {HForm} from '../../jsf/components/HForm';
import {FValidateRegex} from '../../jsf/components/FValidateRegex';
import {HInputText} from '../../jsf/components/HInputText';
import {HMessage} from '../../jsf/components/HMessage';
import {HCommandButton} from '../../jsf/components/HCommandButton';
import {HSelectOneMenu} from '../../jsf/components/HSelectOneMenu';
import {FSelectItem} from '../../jsf/components/FSelectItem';
import {FSelectItems} from '../../jsf/components/FSelectItems';
import {SelectItem} from '../../jsf/objects/SelectItem';
import {HPanelGroup} from '../../jsf/components/HPanelGroup';
import {AceDataTable} from '../../jsf/components/AceDataTable';
import {FFacet} from '../../jsf/components/FFacet';
import {AceColumn} from '../../jsf/components/AceColumn';
import {ApiResponse} from '../../entity/ApiResponse';
import {FlightService} from '../../service/FlightService';

export class FlightOverview extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: {},
      searched: false,
      results: new ApiResponse(0, 10),
    };
    this.options = [];
    this.options.push(new SelectItem('asc', 'Ascending'));
    this.options.push(new SelectItem('desc', 'Descending'));

    this.submit = this.submit.bind(this);
  }

  /**
   * handle form submit
   * @param [currentPage] default 1
   */
  submit(currentPage) {
    // check for form error and re-render messages if required
    if (this.searchForm.hasError()) {
      return;
    }

    (async () => {
      // get form data
      let data = this.searchForm.state.data;

      const limit = this.state.results.limit;
      const offset = currentPage === undefined ?
          0 :
          ((currentPage - 1) * this.state.results.limit);

      let response = await FlightService.getFlights(data.arrivalFilter,
          limit, offset, data.sortOrder);

      this.setState({
        searched: true,
        results: new ApiResponse(offset, limit, response.max, response.data),
      });
    })();
  }

  render() {
    return (
        <React.Fragment>
          <HForm key="0" ref={(form) => {
            this.searchForm = form;
          }} id="searchForm"
                 styleClass="ice-skin-rime contentLevelContainer"
                 data={this.state.data}>
            <div className="inputFieldGroup">
            <span
                className="iceOutTxt headerLabel">Enter Search Criterias</span>
            </div>
            <span
                className="iceOutTxt kdInputFieldLabel minindented">Filter: </span>
            <HInputText id="flightFilterInput"
                        styleClass="iceInpTxt kdInputField"
                        value="arrivalFilter"
                        validatorMessage="Check your input in the field above">
              <FValidateRegex pattern="^[A-Za-zß-üÄ-Ü\.\-\s]*$"/>
            </HInputText>
            <HSelectOneMenu id="sortOrderSelect" styleClass="iceSelOneMnu"
                            value="sortOrder"
                            required={true}
                            requiredMessage="Enter a Date Sort Order"
                            style={{
                              bottom: '3px',
                              position: 'relative',
                              width: '179px',
                            }}>
              <FSelectItem itemLabel="Select One"
                           noSelectionOption={true}/>
              <FSelectItems value={this.options}/>
            </HSelectOneMenu>
            <div className="clear"/>
            <HMessage styleClass="iceMsgError inputFieldLabel"
                      for="flightFilterInput" id="searchTermErrorMessage"/>
            <HMessage styleClass="iceMsgError inputFieldLabel"
                      for="sortOrderSelect" id="sortOrderErrorMessage"/>
            <span className="iceOutTxt iceOutLbl"
                  style={{fontSize: '10px', color: 'black'}}>You can search for Arrival locations</span>
            <div className="clear"/>
            <HCommandButton value="Search"
                            style={{
                              marginTop: '10px',
                            }}
                            action={this.submit}
                            styleClass="iceCmdBtn btnOption"
                            id="flightSearchButton"/>
          </HForm>
          <HForm key="1" id="datatableForm">
            <HPanelGroup layout="block" styleClass="blockArea"
                         style={{width: '1192px'}}
                         rendered={this.state.searched}
                         id="searchWrapper">
              <h2>Flight Overview</h2>
              <AceDataTable id="flightsTable"
                            value={this.state.results}
                            onLoad={this.submit}
                            var="flight" rows={10}
                            paginator={true}>
                <AceColumn>
                  <FFacet name="header">
                    <span className="iceOutTxt">Departure</span>
                  </FFacet>
                  <span
                      className="iceOutTxt center blockArea">#[flight.departure.city]</span>
                </AceColumn>
                <AceColumn>
                  <FFacet name="header">
                    <span className="iceOutTxt">Arrival</span>
                  </FFacet>
                  <span
                      className="iceOutTxt center blockArea">#[flight.arrival.city]</span>
                </AceColumn>
                <AceColumn>
                  <FFacet name="header">
                    <span className="iceOutTxt">Date</span>
                  </FFacet>
                  <span
                      className="iceOutTxt center blockArea">#[flight.dateTime]</span>
                </AceColumn>
                {/*<AceColumn>*/}
                {/*<FFacet name="header">*/}
                {/*<span className="iceOutTxt">Action</span>*/}
                {/*</FFacet>*/}
                {/*<h:panelGrid columns="2">*/}
                {/*<HCommandButton value="View"*/}
                {/*id="viewFlight"*/}
                {/*action="#{flightDetailsBean.viewFlight(flight)}"*/}
                {/*styleClass="iceCmdBtn btnOption"/>*/}
                {/*<HCommandButton value="Book"*/}
                {/*id="bookFlight"*/}
                {/*action="#{bookingBean.startBooking(flight)}"*/}
                {/*styleClass="iceCmdBtn btnOption"/>*/}
                {/*</h:panelGrid>*/}
                {/*</AceColumn>*/}
              </AceDataTable>
            </HPanelGroup>

            <div className="clear"/>
            <hr/>
          </HForm>
        </React.Fragment>
    );
  }
}

// src/main/webapp/angular/app/components/pages/flight-overview/flight-overview.component.ts
import {Component, OnInit} from '@angular/core';
import ApiSearchResponse from '../../../entity/ApiSearchResponse';
import Flight from '../../../entity/Flight';
import {FlightService} from '../../../services/flight.service';
import {SelectItem} from '../../../jsf/objects/select-item';
import {LongDatePipe} from '../../converter/LongDatePipe';

@Component({
  selector: 'app-flight-overview',
  templateUrl: './flight-overview.component.html',
  styleUrls: ['./flight-overview.component.css'],
})
export class FlightOverviewComponent implements OnInit {
  private PAGE_SIZE = 10;
  private flights: ApiSearchResponse<Flight> = new ApiSearchResponse<Flight>();
  private arrivalFilter = '';
  private sortOrder = '';
  private sortOptions: Array<SelectItem> = [];
  private searched = false;
  private dateConverter = new LongDatePipe('de-DE');

  constructor(private flightService: FlightService) {
    this.sortOptions.push(new SelectItem('asc', 'Ascending'));
    this.sortOptions.push(new SelectItem('desc', 'Descending'));

    this.searchFlight = this.searchFlight.bind(this);
  }

  ngOnInit(): void {

  }

  async searchFlight(page: number): Promise<void> {
    this.searched = true;
    this.flights = await this.flightService.getFlights(this.arrivalFilter,
        this.PAGE_SIZE,
        (page - 1) * this.PAGE_SIZE, this.sortOrder);
  }

  viewFlight(flight: Flight) {

  }

  startBooking(flight: Flight) {

  }
}

<h-form id="searchForm" styleClass="ice-skin-rime contentLevelContainer">
  <div class="inputFieldGroup">
    <span class="iceOutTxt headerLabel">Enter Search Criterias</span>
  </div>
  <span class="iceOutTxt kdInputFieldLabel minindented">Filter: </span>
  <h-input-text id="flightFilterInput"
                styleClass="iceInpTxt kdInputField"
                [(ngModel)]="arrivalFilter"
                validatorMessage="Check your input in the field above">
    <f-validate-regex pattern="^[A-Za-zß-üÄ-Ü\.\-\s]*$"></f-validate-regex>
  </h-input-text>
  <h-select-one-menu id="sortOrderSelect" styleClass="iceSelOneMnu"
                     [(ngModel)]="sortOrder"
                     [required]="true" requiredMessage="Enter a Date Sort Order"
                     [style]="{bottom: '3px', position: 'relative', width: '179px'}">
    <f-select-item itemLabel="Select One"
                   [noSelectionOption]="true"></f-select-item>
    <f-select-items [value]="sortOptions"></f-select-items>
  </h-select-one-menu>
  <div class="clear"></div>
  <h-message styleClass="iceMsgError inputFieldLabel"
             for="flightFilterInput" id="searchTermErrorMessage"></h-message>
  <h-message styleClass="iceMsgError inputFieldLabel"
             for="sortOrderSelect" id="sortOrderErrorMessage"></h-message>
  <span class="iceOutTxt iceOutLbl"
        style="font-size: 10px; color: black;">You can search for Arrival locations</span>
  <div class="clear"></div>
  <h-command-button value="Search"
                    [style]="{'margin-top':'10px'}"
                    (action)="searchFlight(1)"
                    styleClass="iceCmdBtn btnOption"
                    id="flightSearchButton"></h-command-button>
</h-form>

<h-form id="datatableForm">
  <h-panel-group layout="block" styleClass="blockArea"
                 [style]="{width: '1192px'}"
                 [rendered]="searched"
                 id="searchWrapper">
    <h2>Flight Overview</h2>

    <ace-data-table id="flightsTable" [value]="flights"
                    var="flight" [rows]="PAGE_SIZE"
                    (onLoad)="searchFlight($event)"
                    [paginator]="true">
      <ace-column>
        <ng-template let-flight>
          <span
              class="iceOutTxt center blockArea">{{flight.departure.city}}</span>
        </ng-template>
        <f-facet name="header">
          <span class="iceOutTxt">Departure</span>
        </f-facet>
      </ace-column>
      <ace-column>
        <ng-template let-flight>
          <span
              class="iceOutTxt center blockArea">{{flight.arrival.city}}</span>
        </ng-template>

        <f-facet name="header">
          <span class="iceOutTxt">Arrival</span>
        </f-facet>
      </ace-column>
      <ace-column>
        <ng-template let-flight>
          <h-output-text value="{{flight.dateTime}}" [converter]="dateConverter"
                         styleClass="iceOutTxt center blockArea"></h-output-text>
        </ng-template>

        <f-facet name="header">
          <span class="iceOutTxt">Date</span>
        </f-facet>
      </ace-column>
      <ace-column>
        <ng-template let-flight>
          <h-panel-grid [columns]="2">
            <f-facet>
              <h-command-button value="View"
                                id="viewFlight"
                                [action]="viewFlight(flight)"
                                styleClass="iceCmdBtn btnOption"></h-command-button>
            </f-facet>
            <f-facet>
              <h-command-button value="Book"
                                id="bookFlight"
                                [action]="startBooking(flight)"
                                styleClass="iceCmdBtn btnOption"></h-command-button>
            </f-facet>
          </h-panel-grid>
        </ng-template>

        <f-facet name="header">
          <span class="iceOutTxt">Action</span>
        </f-facet>
      </ace-column>
    </ace-data-table>
  </h-panel-group>

  <div class="clear"></div>
  <hr/>
  <h-command-button action="/index"
                    value="Back To Home Page"
                    styleClass="iceCmdBtn btnOption"></h-command-button>
</h-form>
