// src/main/webapp/react/jsf/components/IcePanelPopup.js
import React from 'react';
import PropTypes from 'prop-types';
import JsfElement from '../superclass/JsfElement';

export default class IcePanelPopup extends JsfElement {
  static propTypes = {
    id: PropTypes.string,
    styleClass: PropTypes.string,
    visible: PropTypes.bool,
    draggable: PropTypes.bool,
    autoCentre: PropTypes.bool,
  };

  constructor(props, context) {
    super(props, context);

    this.state = {
      width: null,
      height: null,
    };
  }

  componentDidMount() {
    // only do once?
    if (this.state.height === null) {

    }

    this.setState({
      width: this.popup.offsetWidth,
      height: this.popup.offsetHeight,
    });
  }

  render() {
    let style = {
      display: 'block',
      position: 'absolute',
      left: this.state.width ?
          window.innerWidth / 2 - (this.state.width / 2) :
          '0',
      top: this.state.height ?
          window.innerHeight / 2 - (this.state.height / 2) :
          '0',
    };

    if (!this.props.visible) {
      style.display = 'none';
    }

    return (
        <div ref={(div) => this.popup = div}
             className={`icePnlPop ${this.props.styleClass}`}
             id={this.state.id}
             style={style}>
          <table cellPadding="0" cellSpacing="0">
            <tbody>
            <tr id={`${this.state.id}-tr`}>
              <td className="icePnlPopBody popupBody frameHolderBody"
                  colSpan="2">
                {this.body}
              </td>
            </tr>
            </tbody>
          </table>
          <span id={`${this.state.id}script`}/>
        </div>
    );
  }
}
IcePanelPopup.contextTypes = {
  getFormId: PropTypes.func,
};

// src/main/webapp/angular/app/jsf/components/ice-panel-popup/ice-panel-popup.component.ts
import {
  AfterViewInit, Component, ContentChildren, ElementRef, Input, OnChanges,
  OnInit, QueryList, ViewChild,
} from '@angular/core';
import {HFormService} from '../../services/h-form.service';
import JsfElement from '../../superclass/jsf-element';
import {FFacetComponent} from '../f-facet/f-facet.component';

@Component({
  selector: 'ice-panel-popup',
  templateUrl: './ice-panel-popup.component.html',
  styleUrls: ['./ice-panel-popup.component.css'],
})
export class IcePanelPopupComponent extends JsfElement implements OnInit, AfterViewInit, OnChanges {
  @Input()
  visible: boolean;
  @Input()
  draggable: boolean;
  @Input()
  autoCentre: boolean;

  @ViewChild('popup')
  popup: ElementRef;

  private height: number;
  private width: number;

  @ContentChildren(FFacetComponent)
  private facets: QueryList<FFacetComponent>;

  constructor(hFormService: HFormService, elementRef: ElementRef) {
    super(hFormService, elementRef);
  }

  get body(): FFacetComponent {
    for (const facet of this.facets.toArray()) {
      if (facet.name === 'body') {
        return facet;
      }
    }
    return null;
  }

  ngOnInit() {
    this.style = {
      position: 'absolute',
    };
  }

  ngAfterViewInit() {
    super.ngAfterViewInit();
    this.width = this.popup.nativeElement.offsetWidth;
    this.height = this.popup.nativeElement.offsetHeight;
  }

  ngOnChanges() {
    const self = this;

    // we have to use timeout here, as an update in view init is not allowed
    // and we have to manipulate the position after we know the dimensions of the div
    setTimeout(() => {
      self.style.display = self.visible ? 'block' : 'none';
      self.style.left = `${self.width ?
          window.innerWidth / 2 - (self.width / 2) :
          0}px`;
      self.style.top = `${self.height ?
          window.innerHeight / 2 - (self.height / 2) :
          0}px`;
    }, 0);
  }
}

<div #popup class="icePnlPop {{styleClass}}" [id]="id"
     [ngStyle]="style">
  <table cellPadding="0" cellSpacing="0">
    <tbody>
    <tr id={`${this.state.id}-tr`}>
      <td class="icePnlPopBody popupBody frameHolderBody"
          colSpan="2">
        <ng-container [ngTemplateOutlet]="body.content"></ng-container>
      </td>
    </tr>
    </tbody>
  </table>
  <span id="{{id}}script"></span>
</div>
