// src/main/webapp/resources/js/react/jsf/components/HGraphicImage.js
import React from 'react';
import PropTypes from 'prop-types';
import JsfElement from '../superclass/JsfElement';

export default class HGraphicImage extends JsfElement {
  static propTypes = {
    id: PropTypes.string,
    library: PropTypes.string,
    name: PropTypes.string,
  };

  constructor(props, context) {
    super(props, context);
    this.state = {
      id: (context.getFormId) ?
          context.getFormId(this.props.id) :
          this.props.id,
    };
  }

  render() {
    return (
        <img id={this.state.id}
             src={`/javax.faces.resource/${this.props.name}.jsf?ln=${this.props.library}&amp;v=3_3_0_130416`}/>
    );
  }
}

HGraphicImage.contextTypes = {
  getFormId: PropTypes.func,
};

// src/main/webapp/angular/app/jsf/components/h-graphic-image/h-graphic-image.component.ts
import {Component, Input} from '@angular/core';
import {HFormService} from '../../services/h-form.service';
import JsfElement from '../../superclass/jsf-element';

@Component({
  selector: 'h-graphic-image',
  templateUrl: './h-graphic-image.component.html',
  styleUrls: ['./h-graphic-image.component.css'],
})
export class HGraphicImageComponent extends JsfElement {
  @Input()
  library: string;
  @Input()
  name: string;

  constructor(hFormService: HFormService) {
    super(hFormService);
  }
}

<img [id]="id"
     src="/javax.faces.resource/{{name}}.jsf?ln={{library}}&amp;v=3_3_0_130416"
     (click)="onClick()"
/>
