// src/main/webapp/react/components/pages/PassengerForm.js
import React from 'react';
import PropTypes from 'prop-types';
import Flight from '../../entity/Flight';
import {
  CChoose, CIf, COtherwise, CWhen, FAjax, FEvent, FFacet, FSelectItems,
  HCommandButton, HForm, HGraphicImage, HInputText, HMessage, HPanelGroup,
  HSelectOneRadio, IceOutputText, IcePanelPopup, SelectItem, UiDefine,
  ValidationResponse,
} from 'react-jsf/src/index';
import ShortDateConverter from '../../converter/ShortDateConverter';
import Passenger from '../../entity/Passenger';
import IntegerConverter from '../../converter/IntegerConverter';
import PassengerService from '../../service/PassengerService';
import BookingDetails from './BookingDetails';
import BaseTemplate from '../template/BaseTemplate';

export default class PassengerForm extends React.Component {
  static propTypes = {
    selectedFlight: PropTypes.instanceOf(Flight).isRequired,
    cancel: PropTypes.func.isRequired,
    back: PropTypes.func.isRequired,
    bookingFormData: PropTypes.object.isRequired,
  };

  constructor(props, context) {
    super(props, context);

    this.state = {
      passengerFormVisible: true,
      bookingDetailsVisible: false,
      data: this.props.bookingFormData,
      currentPassengerIndex: 0,
      forceEdit: false,
      existingUser: false,
      passportHelp: false,
    };

    this.passengers = [];

    // setup radio items
    this.luggageItems = [];
    this.luggageItems.push(new SelectItem(0, 'No luggage'));
    this.luggageItems.push(new SelectItem(1, '1 Bag'));
    this.luggageItems.push(new SelectItem(2, '2 Bags'));
    this.luggageItems.push(new SelectItem(3, '3 Bags'));

    // create empty passengers
    for (let i = 0; i < this.props.bookingFormData.passengerCount; i++) {
      this.passengers.push(new Passenger());
    }
    // setup first passenger
    this.state.data.currentPassenger = this.passengers[0];

    this.validateForm = this.validateForm.bind(this);
    this.togglePassportHelp = this.togglePassportHelp.bind(this);
    this.passportIdListener = this.passportIdListener.bind(this);
    this.next = this.next.bind(this);
    this.back = this.back.bind(this);
    this.toggleForceEdit = this.toggleForceEdit.bind(this);
  }

  get currentPassenger() {
    return this.passengerForm.state.data.currentPassenger;
  }

  /**
   *
   * @param {Passenger} passenger
   */
  set currentPassenger(passenger) {
    this.passengerForm.state.data.currentPassenger = passenger;
  }

  async next() {
    // save current data
    this.state.data = this.passengerForm.state.data;
    // save entered passenger data
    this.passengers[this.state.currentPassengerIndex] = this.currentPassenger;

    if (this.state.currentPassengerIndex + 1 === this.passengers.length) {
      return this.setState({
        passengerFormVisible: false,
        bookingDetailsVisible: true,
      });
    }

    // increase index
    this.state.currentPassengerIndex++;
    this.state.data.currentPassenger = this.passengers[this.state.currentPassengerIndex];

    // inform about change
    this.setState({
      data: this.state.data,
      forceEdit: false,
      existingUser: false,
      currentPassengerIndex: this.state.currentPassengerIndex,
    });
  }

  back() {
    // did we trigger back function on next page
    if (this.state.bookingDetailsVisible) {
      return this.setState({
        passengerFormVisible: true,
        bookingDetailsVisible: false,
      });
    }

    // save current data
    this.state.data = this.passengerForm.state.data;
    // save entered passenger data
    this.passengers[this.state.currentPassengerIndex] = this.currentPassenger;

    if (this.state.currentPassengerIndex === 0) {
      return this.props.back();
    }

    // decrease index
    this.state.currentPassengerIndex--;
    // set last passenger as current
    this.state.data.currentPassenger = this.passengers[this.state.currentPassengerIndex];

    // inform about change
    this.setState({
      data: this.state.data,
      forceEdit: false,
      existingUser: false,
      currentPassengerIndex: this.state.currentPassengerIndex,
    });
  }

  toggleForceEdit() {
    this.setState({
      forceEdit: !this.state.forceEdit,
    });
  }

  /**
   * check for duplicated passengers
   */
  validateForm() {
    let key;
    if (!this.props.selectedFlight.foreignTravel()) {
      key = 'idCardNumber';
    } else {
      key = 'passportNumber';
    }

    let found = 0;
    for (let passenger of this.passengers) {
      if (passenger[key] && passenger[key]
          === this.currentPassenger[key]) {
        found++;
      }
    }

    return new ValidationResponse(found > 1,
        'This passenger is already registered', key + 'Input');
  }

  togglePassportHelp() {
    this.setState({
      passportHelp: !this.state.passportHelp,
    });
  }

  /**
   *
   * @param {Input} input
   * @param {string} render
   */
  async passportIdListener(input, render) {
    // only get when something was entered
    if (this.currentPassenger.passportNumber !== '' ||
        this.currentPassenger.idCardNumber !== '') {
      let passengers = await PassengerService.getPassengers(
          input.props.id === 'passportNumberInput' ?
              this.currentPassenger.passportNumber :
              '',
          input.props.id === 'idCardNumberInput' ?
              this.currentPassenger.idCardNumber :
              '');
      if (passengers) {
        this.currentPassenger = passengers[0];
        this.setState({
          data: this.state.data,
          existingUser: true,
          forceEdit: false,
        });
      }
    }
  }

  render() {
    if (this.state.passengerFormVisible) {
      // use passenger index as key, so the form re-mounts after next/back
      return (
          <BaseTemplate>
            <UiDefine name='content'>
              <HForm key={this.state.currentPassengerIndex} ref={(form) => {
                this.passengerForm = form;
              }} id="passengerData" styleClass="ice-skin-rime"
                     data={this.state.data}>
                <FEvent id="multiFieldValidationEvent"
                        listener={this.validateForm}
                        type="postValidate"/>
                <div className="inputFieldGroup">
              <span
                  className="iceOutTxt headerLabel">Enter Data for Passenger #{this.state.currentPassengerIndex +
              1}</span>
                </div>
                <HPanelGroup id="passportContainer" layout="block"
                             styleClass="contentLevelContainer blockArea">
                  <div className="lFloat indented inputFieldGroup">
                    <CChoose>
                      <CWhen
                          test={this.props.selectedFlight.foreignTravel()}>
                        <span
                            className="iceOutTxt masInfoFieldLabel minindented">Passport Number:</span>
                        <HInputText id="passportNumberInput" maxlength={6}
                                    value="currentPassenger.passportNumber"
                                    required={true}
                                    requiredMessage="Insert your Passport Number">
                          <FAjax event="blur"
                                 listener={this.passportIdListener}
                                 execute="@this"
                                 render="@form"/>
                        </HInputText>
                      </CWhen>
                      <COtherwise>
                        <span
                            className="iceOutTxt masInfoFieldLabel minindented">Id Card Number:</span>
                        <HInputText id="idCardNumberInput" maxlength={5}
                                    value="currentPassenger.idCardNumber"
                                    required={true}
                                    requiredMessage="Insert your Id Card Number">
                          <FAjax event="blur"
                                 listener={this.passportIdListener}
                                 execute="@this"
                                 render="@form"/>
                        </HInputText>
                      </COtherwise>
                    </CChoose>
                    <HGraphicImage id="helpIcon" library="images"
                                   name="icon_info.gif"
                                   onclick={this.togglePassportHelp}/>
                  </div>

                  <div className="clear"/>
                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="idCardNumberInput" id="idCardErrorMessage"/>
                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="passportNumberInput"
                            id="passportErrorMessage"/>
                </HPanelGroup>
                <HPanelGroup id="personalDataContainer" layout="block"
                             styleClass="contentLevelContainer blockArea">
                  <CIf test={this.state.existingUser}>
                    <div className="indented inputFieldGroup">
                      <HCommandButton id="forceEditButton" value="Edit Data"
                                      styleClass="iceCmdBtn btnOption"
                                      action={this.toggleForceEdit}>
                      </HCommandButton>
                    </div>
                  </CIf>
                  <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Firstname:</span>
                    <HInputText id="firstNameInput"
                                disabled={this.state.existingUser &&
                                !this.state.forceEdit}
                                value="currentPassenger.firstName"
                                required={true}
                                requiredMessage="Insert your Firstname"/>
                  </div>
                  <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Lastname:</span>
                    <HInputText id="lastNameInput"
                                disabled={this.state.existingUser &&
                                !this.state.forceEdit}
                                value="currentPassenger.lastName"
                                required={true}
                                requiredMessage="Insert your Lastname"/>
                  </div>
                  <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Birthdate:</span>
                    <HInputText id="birthDateInput"
                                disabled={this.state.existingUser &&
                                !this.state.forceEdit}
                                value="currentPassenger.birthDay"
                                required={true}
                                requiredMessage="Insert your Birthdate"
                                converter={ShortDateConverter}
                                converterMessage="Enter a date with format dd.MM.yyyy"/>
                  </div>
                  <div className="clear"/>
                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="firstNameInput" id="firstNameErrorMessage"/>
                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="lastNameInput" id="lastNameErrorMessage"/>
                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="birthDateInput" id="birthDateErrorMessage"/>
                </HPanelGroup>
                <HPanelGroup id="luggageContainer" layout="block"
                             styleClass="contentLevelContainer blockArea">
                  <span className="iceOutTxt masInfoFieldLabel minindented">Select the desired amount of luggage</span>
                  <HSelectOneRadio id="luggageRadio"
                                   styleClass="iceSelOneRb masInfoInputField"
                                   required={true}
                                   layout="pageDirection"
                                   requiredMessage="Select the amount of luggage you want to check in"
                                   converter={IntegerConverter}
                                   value="currentPassenger.luggageCount">
                    <FSelectItems id="luggageNumbers"
                                  value={this.luggageItems}/>
                  </HSelectOneRadio>
                  <div className="clear"/>
                </HPanelGroup>

                <HCommandButton value="Cancel"
                                immediate={true}
                                action={this.props.cancel}
                                id="cancelBookingButton"
                                styleClass="iceCmdBtn btnOption"/>
                <HCommandButton immediate={true} action={this.back}
                                value="Back"
                                id="backButton"
                                styleClass="iceCmdBtn btnOption"/>
                <HCommandButton value="Continue"
                                id="continueButton"
                                action={this.next}
                                styleClass="iceCmdBtn btnOption"/>

                <IcePanelPopup id="passportHelpPopup"
                               visible={this.state.passportHelp}
                               draggable={false}
                               styleClass="popup frameHolder" autoCentre={true}>
                  <FFacet name="body">
                    <div id="iFrameWrapper">
                      <IceOutputText styleClass="iceOutTxt">
                        Your passport number should start with P and consist of
                        5
                        numbers <br/>
                        Your id card number should consist of 5 numbers
                      </IceOutputText>
                    </div>
                  </FFacet>
                </IcePanelPopup>
              </HForm>
            </UiDefine>
          </BaseTemplate>
      );
    } else {
      let data = this.state.data;
      data.passengers = this.passengers;
      return <BookingDetails back={this.back} cancel={this.props.cancel}
                             selectedFlight={this.props.selectedFlight}
                             data={data}/>;
    }
  }
}

// src/main/webapp/angular/app/components/pages/passenger-form/passenger-form.component.ts
import {Component, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import Passenger from '../../../entity/Passenger';
import {SelectItem} from '../../../jsf/objects/select-item';
import {ConversationService} from '../../../jsf/services/conversation.service';
import {PassengerService} from '../../../services/passenger.service';

@Component({
  selector: 'app-passenger-form',
  templateUrl: './passenger-form.component.html',
  styleUrls: ['./passenger-form.component.css'],
})
export class PassengerFormComponent implements OnInit {
  private currentPassengerIndex: 0;
  private forceEdit = false;
  private existingUser = false;
  private passportHelp = false;
  private passengers: Array<Passenger> = [];
  private luggageItems: Array<SelectItem> = [];

  constructor(
      private passengerService: PassengerService,
      private router: Router,
      private conversationService: ConversationService) {
    // setup radio items
    this.luggageItems.push(new SelectItem(0, 'No luggage'));
    this.luggageItems.push(new SelectItem(1, '1 Bag'));
    this.luggageItems.push(new SelectItem(2, '2 Bags'));
    this.luggageItems.push(new SelectItem(3, '3 Bags'));

    if (!this.conversationService.isActive()) {
      console.error('attempted to visit site without selecting a flight');
      router.navigateByUrl('pages/flightOverview').then().catch((e) => {
        console.error(e);
      });
    } else if (!this.conversationService.conversation.hasProperty(
            'passengers')) {
      // create empty passengers
      for (let i = 0; i <
      this.conversationService.conversation.getProperty(
          'passengerCount'); i++) {
        this.passengers.push(new Passenger());
      }
    } else {
      this.passengers = this.conversationService.conversation.getProperty(
          'passengers');
    }
  }

  get currentPassenger(): Passenger {
    return this.passengers[this.currentPassengerIndex];
  }

  set currentPassenger(passenger: Passenger) {
    this.passengers[this.currentPassengerIndex] = passenger;
  }

  ngOnInit() {
  }

  async next() {
    if (this.currentPassengerIndex + 1 === this.passengers.length) {
      try {
        return await this.router.navigateByUrl('pages/bookingDetails');
      } catch (e) {
        console.error(e);
      }
    }

    // increase index
    this.currentPassengerIndex++;
    this.forceEdit = false;
    this.existingUser = false;
  }

  async back() {
    // did we trigger back function on next page
    // save current data

    if (this.currentPassengerIndex === 0) {
      try {
        return await this.router.navigateByUrl('pages/bookingForm');
      } catch (e) {
        console.error(e);
      }
    }

    // decrease index
    this.currentPassengerIndex--;
    this.forceEdit = false;
    this.existingUser = false;
  }

  toggleForceEdit() {
    this.forceEdit = !this.forceEdit;
  }

  togglePassportHelp() {
    this.passportHelp = !this.passportHelp;
  }

  /**
   *
   * @param {Input} input
   * @param {string} render
   */
  async passportIdListener(input, render) {
    // only get when something was entered
    if (this.currentPassenger.passportNumber !== '' ||
        this.currentPassenger.idCardNumber !== '') {
      const passengers = await this.passengerService.getPassengers(
          input.props.id === 'passportNumberInput' ?
              this.currentPassenger.passportNumber :
              '',
          input.props.id === 'idCardNumberInput' ?
              this.currentPassenger.idCardNumber :
              '');
      if (passengers) {
        this.currentPassenger = passengers[0];
        this.forceEdit = false;
        this.existingUser = true;
      }
    }
  }

}

<h:form id="passengerData" styleClass="ice-skin-rime">
  <div class="inputFieldGroup">
    <span class="iceOutTxt headerLabel">Enter Data for Passenger ##{passengerFormBean.currentPassengerIndex + 1}</span>
  </div>
  <f:event id="multiFieldValidationEvent"
           listener="#{passengerFormBean.validateForm}" type="postValidate"/>

  <!-- id number or passport id -->
  <h:panelGroup id="passportContainer" layout="block"
                styleClass="contentLevelContainer blockArea">
    <div class="lFloat indented inputFieldGroup">
      <c:choose>
        <!-- if other country -->
        <c:when test="#{bookingFormBean.selectedFlight.foreignTravel()}">
          <!-- passport -->
          <span
              class="iceOutTxt masInfoFieldLabel minindented">Passport Number:</span>
          <h:inputText id="passportNumberInput" maxlength="6"
                       value="#{passengerFormBean.currentPassenger.passportNumber}"
                       required="true"
                       requiredMessage="Insert your Passport Number">
            <f:ajax event="blur"
                    listener="#{passengerFormBean.passportIdListener}"
                    execute="@this"
                    render="@form"/>
          </h:inputText>
        </c:when>
        <c:otherwise>
          <!-- id card -->
          <span
              class="iceOutTxt masInfoFieldLabel minindented">Id Card Number:</span>
          <h:inputText id="idCardNumberInput" maxlength="5"
                       value="#{passengerFormBean.currentPassenger.idCardNumber}"
                       required="true"
                       requiredMessage="Insert your Id Card Number">
            <f:ajax event="blur"
                    listener="#{passengerFormBean.passportIdListener}"
                    execute="@this"
                    render="@form"/>
          </h:inputText>
        </c:otherwise>
      </c:choose>
      <h:graphicImage id="helpIcon" library="images"
                      name="icon_info.gif">
        <f:ajax render="@all" event="click"
                listener="#{passengerFormBean.setPassportHelp}"/>
      </h:graphicImage>
    </div>

    <div class="clear"/>
  </h:panelGroup>
  <!-- ajax for prefilling data when id exists -->
  <!-- validate numbers if existing check existing data for correctness -->
  <h:panelGroup id="personalDataContainer" layout="block"
                styleClass="contentLevelContainer blockArea">
    <!-- if number exists show force edit button -->
    <c:if test="#{passengerFormBean.existingUser}">
      <div class="indented inputFieldGroup">
        <h:commandButton id="forceEditButton" value="Edit Data"
                         styleClass="iceCmdBtn btnOption">
          <f:ajax render="@form" execute="@this"
                  listener="#{passengerFormBean.forceEditListener}"/>
        </h:commandButton>
      </div>
    </c:if>
    <!-- Firstname -->
    <div class="lFloat indented inputFieldGroup">
      <span class="iceOutTxt masInfoFieldLabel minindented">Firstname:</span>
      <h:inputText id="firstNameInput"
                   disabled="#{passengerFormBean.existingUser and !passengerFormBean.forceEdit}"
                   value="#{passengerFormBean.currentPassenger.firstName}"
                   required="true"
                   requiredMessage="Insert your Firstname"/>
    </div>
    <!-- Lastname -->
    <div class="lFloat indented inputFieldGroup">
      <span class="iceOutTxt masInfoFieldLabel minindented">Lastname:</span>
      <h:inputText id="lastNameInput"
                   disabled="#{passengerFormBean.existingUser and !passengerFormBean.forceEdit}"
                   value="#{passengerFormBean.currentPassenger.lastName}"
                   required="true"
                   requiredMessage="Insert your Lastname"/>
    </div>
    <!-- Birthday with dp + converter -->
    <div class="lFloat indented inputFieldGroup">
      <span class="iceOutTxt masInfoFieldLabel minindented">Birthdate:</span>
      <h:inputText id="birthDateInput"
                   disabled="#{passengerFormBean.existingUser and !passengerFormBean.forceEdit}"
                   value="#{passengerFormBean.currentPassenger.birthDay}"
                   required="true"
                   requiredMessage="Insert your Birthdate"
                   converter="de.uni.frankfurt.ShortDateConverter"/>
    </div>
    <div class="clear"/>
  </h:panelGroup>

  <!-- luggage radio -->
  <h:panelGroup id="luggageContainer" layout="block"
                styleClass="contentLevelContainer blockArea">
    <span class="iceOutTxt masInfoFieldLabel minindented">Select the desired amount of luggage</span>
    <h:selectOneRadio id="luggageRadio"
                      styleClass="iceSelOneRb masInfoInputField" required="true"
                      layout="pageDirection"
                      requiredMessage="Select the amount of luggage you want to check in"
                      value="#{passengerFormBean.currentPassenger.luggageCount}">
      <f:selectItems id="luggageNumbers"
                     value="#{passengerFormBean.luggageItems}"/>
    </h:selectOneRadio>
    <div class="clear"/>
    <h:message styleClass="iceMsgError inputFieldLabel"
               for="firstNameInput" id="firstNameErrorMessage"/>
    <h:message styleClass="iceMsgError inputFieldLabel"
               for="lastNameInput" id="lastNameErrorMessage"/>
    <h:message styleClass="iceMsgError inputFieldLabel"
               for="birthDateInput" id="birthDateErrorMessage"/>
    <h:message styleClass="iceMsgError inputFieldLabel"
               for="idCardNumberInput" id="idCardErrorMessage"/>
    <h:message styleClass="iceMsgError inputFieldLabel"
               for="passportNumberInput" id="passportErrorMessage"/>
  </h:panelGroup>

  <h:commandButton value="Cancel"
                   action="#{bookingBean.cancelBooking}"
                   id="cancelBookingButton"
                   styleClass="iceCmdBtn btnOption"/>
  <h:commandButton immediate="true" action="#{passengerFormBean.back}"
                   value="Back"
                   id="backButton"
                   styleClass="iceCmdBtn btnOption"/>
  <h:commandButton value="Continue"
                   id="continueButton"
                   action="#{passengerFormBean.next}"
                   styleClass="iceCmdBtn btnOption"/>

  <ice:panelPopup id="passportHelpPopup"
                  visible="#{passengerFormBean.passportHelp}" draggable="false"
                  styleClass="popup frameHolder" autoCentre="true">
    <f:facet name="body">
      <div id="iFrameWrapper">
        <ice:outputText styleClass="iceOutTxt">
          Your passport number should start with P and constist of 5 numbers
          <br/>
          Your id card number should consist of 5 numbers
        </ice:outputText>
      </div>
    </f:facet>
  </ice:panelPopup>
</h:form>
