// src/main/webapp/angular/app/jsf/components/f-convert-number/f-convert-number.component.ts
import {Component, Input} from '@angular/core';
import {Converter} from '../../superclass/converter';
import {JsfCore} from '../../superclass/jsf-core';

@Component({
  selector: 'f-convert-number',
  templateUrl: './f-convert-number.component.html',
  styleUrls: ['./f-convert-number.component.css'],
})
export class FConvertNumberComponent extends JsfCore implements Converter {
  @Input()
  pattern: string;
  @Input()
  groupingUsed: boolean;
  @Input()
  locale = 'de-DE';

  constructor() {
    super();
  }

  transformToObject(value: string): any {
    return null;
  }

  transform(value: any): string | null {
    // TODO proper parsing of the decimal java format
    const pattern = this.pattern.split(',');
    return value.toLocaleString(this.locale, {
      minimumFractionDigits: pattern[1].length,
      maximumFractionDigits: pattern[1].length,
      minimumIntegerDigits: pattern[0].length,
      useGrouping: this.groupingUsed,
    });
  }
}

// src/main/webapp/resources/js/react/jsf/components/FConvertNumber.js
import React from 'react';
import PropTypes from 'prop-types';

export default class FConvertNumber extends React.Component {
  static propTypes = {
    pattern: PropTypes.string.isRequired,
    groupingUsed: PropTypes.bool.isRequired,
    locale: PropTypes.string.isRequired,
  };

  constructor(props, context) {
    super(props, context);

    this.convert = this.convert.bind(this);
  }

  /**
   *
   * @param {number} content
   * @return {string}
   */
  convert(content) {
    const pattern = this.props.pattern.split(',');
    return content.toLocaleString(this.props.locale, {
      minimumFractionDigits: pattern[1].length,
      minimumIntegerDigits: pattern[0].length,
      useGrouping: this.props.groupingUsed,
    });
  }
}
