// src/main/webapp/angular/app/components/cc/cc-flight-details/cc-flight-details.component.ts
import {Component, Input} from '@angular/core';
import {LongDatePipe} from '../../../converter/long-date-pipe';
import Flight from '../../../entity/Flight';

@Component({
  selector: 'cc-flight-details',
  templateUrl: './cc-flight-details.component.html',
  styleUrls: ['./cc-flight-details.component.css'],
})
export class CCFlightDetailsComponent {
  @Input()
  flight: Flight;

  @Input()
  headline: boolean;

  @Input()
  standalone: boolean;

  private dateConverter = new LongDatePipe('de-DE');

  constructor() {
  }
}

<h-panel-group layout="block"
               styleClass="contentLevelContainer blockArea"
               id="flightDetailsContainer">
    <ui-fragment [rendered]="headline">
        <div class="inputFieldGroup">
            <span class="iceOutTxt headerLabel">Flight Details</span>
        </div>
    </ui-fragment>
    <h-panel-group layout="block">
        <div class="clear" style="height: 6px;"></div>
        <div class="inputFieldGroup minindented">
                    <span class="iceOutTxt kdInputFieldLabel"
                          style="width: 200px;">Flight Type</span>
            <c-choose>
                <!-- if other country -->
                <c-when [test]="flight.foreignTravel()">
                            <span class="iceOutTxt kdInputFieldLabel"
                                  style="width: 200px;">International Flight</span>
                </c-when>
                <c-otherwise>
                            <span class="iceOutTxt kdInputFieldLabel"
                                  style="width: 200px;">National Flight</span>
                </c-otherwise>
            </c-choose>
            <br/>
            <span class="iceOutTxt kdInputFieldLabel"
                  style="width: 200px;">Aircraft Model:</span>
            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                           [value]="flight.aircraft.model"></h-output-text>
            <span class="iceOutTxt kdInputFieldLabel"
                  style="width: 200px;">Departure Airport:</span>
            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                           [value]="flight.departure.code + ' ' + flight.departure.city"></h-output-text>
            <span class="iceOutTxt kdInputFieldLabel"
                  style="width: 200px;">Arrival Airport:</span>
            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                           [value]="flight.arrival.code + ' ' + flight.arrival.city"></h-output-text>
            <span class="iceOutTxt kdInputFieldLabel"
                  style="width: 200px;">Departure Time:</span>
            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                           [value]="flight.dateTime"
                           [converter]="dateConverter"></h-output-text>
        </div>
    </h-panel-group>
</h-panel-group>

<c-if [test]="standalone">
    <h-form id="pageNav">
        <h-command-button value="Back"
                          id="backButton"
                          action="/pages/flightOverview"
                          styleClass="iceCmdBtn btnOption"></h-command-button>
    </h-form>
</c-if>

// src/main/webapp/react/components/cc/CCFlightDetails.js
import React from 'react';
import PropTypes from 'prop-types';
import {
  CChoose, CIf, COtherwise, CWhen, HCommandButton, HForm, HOutputText,
  HPanelGroup, UIFragment,
} from 'react-jsf';
import Flight from '../../entity/Flight';
import DateConverter from '../../converter/DateConverter';

export default class CCFlightDetails extends React.Component {
  static propTypes = {
    flight: PropTypes.instanceOf(Flight).isRequired,
    headline: PropTypes.bool,
    standalone: PropTypes.bool,
    back: PropTypes.func,
  };

  render() {
    return (
        <div>
          <HPanelGroup layout="block"
                       styleClass="contentLevelContainer blockArea"
                       id="flightDetailsContainer">
            <UIFragment rendered={this.props.headline}>
              <div className="inputFieldGroup">
                <span className="iceOutTxt headerLabel">Flight Details</span>
              </div>
            </UIFragment>
            <HPanelGroup layout="block">
              <div className="clear" style={{height: '6px'}}/>
              <div className="inputFieldGroup minindented">
                    <span className="iceOutTxt kdInputFieldLabel"
                          style={{width: '200px'}}>Flight Type</span>
                <CChoose>
                  <CWhen test={this.props.flight.foreignTravel()}>
                            <span className="iceOutTxt kdInputFieldLabel"
                                  style={{width: '200px'}}>International Flight</span>
                  </CWhen>
                  <COtherwise>
                            <span className="iceOutTxt kdInputFieldLabel"
                                  style={{width: '200px'}}>National Flight</span>
                  </COtherwise>
                </CChoose>
                <br/>
                <br/>
                <span className="iceOutTxt kdInputFieldLabel"
                      style={{width: '200px'}}>Aircraft Model:</span>
                <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                             value={this.props.flight.aircraft.model}/>
                <span className="iceOutTxt kdInputFieldLabel"
                      style={{width: '200px'}}>Departure Airport:</span>
                <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                             value={this.props.flight.departure.code + ' ' +
                             this.props.flight.departure.city}/>
                <span className="iceOutTxt kdInputFieldLabel"
                      style={{width: '200px'}}>Arrival Airport:</span>
                <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                             value={this.props.flight.arrival.code + ' ' +
                             this.props.flight.arrival.city}/>
                <span className="iceOutTxt kdInputFieldLabel"
                      style={{width: '200px'}}>Departure Time:</span>
                <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                             value={this.props.flight.dateTime}
                             converter={DateConverter}/>
              </div>
            </HPanelGroup>
          </HPanelGroup>

          <CIf test={this.props.standalone}>
            <HForm id="pageNav">
              <HCommandButton value="Back"
                              id="backButton"
                              action={this.props.back}
                              styleClass="iceCmdBtn btnOption"/>
            </HForm>
          </CIf>
        </div>
    );
  }
}
