// src/main/webapp/angular/app/pages/flight-overview/flight-overview.component.ts
import {Component, OnInit} from '@angular/core';
import {SortOrder} from '../../enums/SortOrder';
import ApiSearchResponse from '../../entity/ApiSearchResponse';
import Flight from '../../entity/Flight';
import {FlightService} from '../../services/flight.service';

@Component({
  selector: 'app-flight-overview',
  templateUrl: './flight-overview.component.html',
  styleUrls: ['./flight-overview.component.css'],
})
export class FlightOverviewComponent implements OnInit {
  flights: ApiSearchResponse<Flight>;
  arrivalFilter: string;

  constructor(private flightService: FlightService) {
  }

  async ngOnInit() {
    this.flights = await this.flightService.getFlights('Berlin', 100, 0,
        SortOrder.asc);
  }

}

<h-form id="searchForm"
        styleClass="ice-skin-rime contentLevelContainer">
  <div class="inputFieldGroup">
            <span
                class="iceOutTxt headerLabel">Enter Search Criterias</span>
  </div>
  <span
      class="iceOutTxt kdInputFieldLabel minindented">Filter: </span>
  <h-input-text id="flightFilterInput"
                styleClass="iceInpTxt kdInputField"
                [(ngModel)]="arrivalFilter"
                validatorMessage="Check your input in the field above">
  </h-input-text>
  <h-message for="flightFilterInput" id="test"></h-message>
</h-form>

// src/main/webapp/resources/js/react/components/pages/FlightOverview.js
import React from 'react';
import {HForm} from '../../jsf/HForm';
import {FValidateRegex} from '../../jsf/FValidateRegex';
import {FlightOverviewFormData} from '../../entity/FlightOverviewFormData';
import {HInputText} from '../../jsf/HInputText';
import {HMessage} from '../../jsf/HMessage';

export class FlightOverview extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      data: new FlightOverviewFormData(),
    };

    this.setArrivalFilter = this.setArrivalFilter.bind(this);
  }

  get data() {
    return this.state.data;
  }

  /**
   * combined getter and setter for form data
   * @param {string} name
   * @returns {string}
   */
  setArrivalFilter(name) {
    if (name === undefined) {
      return this.data.arrivalFilter;
    } else {
      this.data.arrivalFilter = name;
    }
    this.setState({
      data: this.data,
    });
  }

  render() {
    return (
        <HForm id="searchForm" styleClass="ice-skin-rime contentLevelContainer">
          <div className="inputFieldGroup">
            <span
                className="iceOutTxt headerLabel">Enter Search Criterias</span>
          </div>
          <span
              className="iceOutTxt kdInputFieldLabel minindented">Filter: </span>
          <HInputText id="flightFilterInput"
                      styleClass="iceInpTxt kdInputField"
                      value={this.setArrivalFilter}
                      validatorMessage="Check your input in the field above">
            <FValidateRegex pattern="^[A-Za-zß-üÄ-Ü\.\-\s]*$"/>
          </HInputText>
          <HMessage styleClass="iceMsgError inputFieldLabel"
                    for="flightFilterInput" id="searchTermErrorMessage"/>
        </HForm>);
  }
}
