// src/main/webapp/angular/app/components/pages/passenger-form/passenger-form.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'passenger-form',
  templateUrl: './passenger-form.component.html',
  styleUrls: ['./passenger-form.component.css'],
})
export class PassengerFormComponent implements OnInit {

  constructor() {
  }

  ngOnInit() {
  }

}

<h-body>
    <app-base-template>
        <ui-define name="content">
            <h-form id="passengerData" styleClass="ice-skin-rime">
                <div class="inputFieldGroup">
                    <span class="iceOutTxt headerLabel">Enter Data for Passenger #{{currentPassengerIndex + 1}}</span>
                </div>
                <f-event id="multiFieldValidationEvent"
                         [listener]="validateForm" type="postValidate"></f-event>

                <!-- id number or passport id -->
                <h-panel-group id="passportContainer" layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <div class="lFloat indented inputFieldGroup">
                        <c-choose>
                            <!-- if other country -->
                            <c-when [test]="selectedFlight.foreignTravel()">
                                <!-- passport -->
                                <span
                                        class="iceOutTxt masInfoFieldLabel minindented">Passport Number:</span>
                                <h-input-text id="passportNumberInput" maxlength="6"
                                              [(ngModel)]="currentPassenger.passportNumber"
                                              [required]="true"
                                              requiredMessage="Insert your Passport Number">
                                    <f-ajax event="blur"
                                            (listener)="passportIdListener($event)"
                                            execute="@this"
                                            render="@form"></f-ajax>
                                </h-input-text>
                            </c-when>
                            <c-otherwise>
                                <!-- id card -->
                                <span
                                        class="iceOutTxt masInfoFieldLabel minindented">Id Card Number:</span>
                                <h-input-text id="idCardNumberInput" [maxLength]="5"
                                              [(ngModel)]="currentPassenger.idCardNumber"
                                              required="true"
                                              requiredMessage="Insert your Id Card Number">
                                    <f-ajax event="blur"
                                            (listener)="passportIdListener($event)"
                                            execute="@this"
                                            render="@form"></f-ajax>
                                </h-input-text>
                            </c-otherwise>
                        </c-choose>
                        <h-graphic-image id="helpIcon" library="images"
                                         name="icon_info.gif">
                            <f-ajax render="@all" event="click"
                                    (listener)="togglePassportHelp($event)"></f-ajax>
                        </h-graphic-image>
                    </div>

                    <div class="clear"></div>
                </h-panel-group>
                <!-- ajax for prefilling data when id exists -->
                <!-- validate numbers if existing check existing data for correctness -->
                <h-panel-group id="personalDataContainer" layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <!-- if number exists show force edit button -->
                    <c-if [test]="existingUser">
                        <div class="indented inputFieldGroup">
                            <h-command-button id="forceEditButton" value="Edit Data"
                                              styleClass="iceCmdBtn btnOption">
                                <f-ajax render="@form" execute="@this"
                                        (listener)="toggleForceEdit($event)"></f-ajax>
                            </h-command-button>
                        </div>
                    </c-if>
                    <!-- Firstname -->
                    <div class="lFloat indented inputFieldGroup">
                        <span class="iceOutTxt masInfoFieldLabel minindented">Firstname:</span>
                        <h-input-text id="firstNameInput"
                                      [disabled]="existingUser && !forceEdit"
                                      [(ngModel)]="currentPassenger.firstName"
                                      [required]="true"
                                      requiredMessage="Insert your Firstname"></h-input-text>
                    </div>
                    <!-- Lastname -->
                    <div class="lFloat indented inputFieldGroup">
                        <span class="iceOutTxt masInfoFieldLabel minindented">Lastname:</span>
                        <h-input-text id="lastNameInput"
                                      [disabled]="existingUser && !forceEdit"
                                      [(ngModel)]="currentPassenger.lastName"
                                      [required]="true"
                                      requiredMessage="Insert your Lastname"></h-input-text>
                    </div>
                    <!-- Birthday with dp + converter -->
                    <div class="lFloat indented inputFieldGroup">
                        <span class="iceOutTxt masInfoFieldLabel minindented">Birthdate:</span>
                        <h-input-text id="birthDateInput"
                                      [disabled]="existingUser && !forceEdit"
                                      [(ngModel)]="currentPassenger.birthDay"
                                      [required]="true"
                                      requiredMessage="Insert your Birthdate"
                                      [converter]="shortDateConverter"></h-input-text>
                    </div>
                    <div class="clear"></div>
                </h-panel-group>

                <!-- luggage radio -->
                <h-panel-group id="luggageContainer" layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <span class="iceOutTxt masInfoFieldLabel minindented">Select the desired amount of luggage</span>
                    <h-select-one-radio id="luggageRadio"
                                        styleClass="iceSelOneRb masInfoInputField"
                                        [required]="true"
                                        layout="pageDirection"
                                        requiredMessage="Select the amount of luggage you want to check in"
                                        [(ngModel)]="currentPassenger.luggageCount"
                                        [converter]="integerConverter">
                        <f-select-items id="luggageNumbers"
                                        [value]="luggageItems"></f-select-items>
                    </h-select-one-radio>
                    <div class="clear"></div>
                    <h-message styleClass="iceMsgError inputFieldLabel"
                               for="firstNameInput" id="firstNameErrorMessage"></h-message>
                    <h-message styleClass="iceMsgError inputFieldLabel"
                               for="lastNameInput" id="lastNameErrorMessage"></h-message>
                    <h-message styleClass="iceMsgError inputFieldLabel"
                               for="birthDateInput" id="birthDateErrorMessage"></h-message>
                    <h-message styleClass="iceMsgError inputFieldLabel"
                               for="idCardNumberInput" id="idCardErrorMessage"></h-message>
                    <h-message styleClass="iceMsgError inputFieldLabel"
                               for="passportNumberInput"
                               id="passportErrorMessage"></h-message>
                </h-panel-group>

                <h-command-button value="Cancel"
                                  [immediate]="true"
                                  (action)="cancelBooking()"
                                  id="cancelBookingButton"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>
                <h-command-button [immediate]="true" (action)="back()"
                                  value="Back"
                                  id="backButton"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>
                <h-command-button value="Continue"
                                  id="continueButton"
                                  (action)="next()"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>

                <ice-panel-popup id="passportHelpPopup"
                                 [visible]="passportHelp"
                                 [draggable]="false"
                                 styleClass="popup frameHolder" [autoCentre]="true">
                    <f-facet name="body">
                        <div id="iFrameWrapper">
                            <ice-output-text styleClass="iceOutTxt">
                                Your passport number should start with P and constist of 5 numbers
                                <br/>
                                Your id card number should consist of 5 numbers
                            </ice-output-text>
                        </div>
                    </f-facet>
                </ice-panel-popup>
            </h-form>
        </ui-define>
    </app-base-template>
</h-body>

// src/main/webapp/resources/js/react/components/pages/PassengerForm.js
import React from 'react';
import PropTypes from 'prop-types';
import HForm from '../../jsf/components/HForm';
import Flight from '../../entity/Flight';
import HPanelGroup from '../../jsf/components/HPanelGroup';
import HInputText from '../../jsf/components/HInputText';
import FFacet from '../../jsf/components/FFacet';
import HMessage from '../../jsf/components/HMessage';
import HCommandButton from '../../jsf/components/HCommandButton';
import CWhen from '../../jsf/components/CWhen';
import FAjax from '../../jsf/components/FAjax';
import COtherwise from '../../jsf/components/COtherwise';
import CIf from '../../jsf/components/CIf';
import HGraphicImage from '../../jsf/components/HGraphicImage';
import FSelectItems from '../../jsf/components/FSelectItems';
import ShortDateConverter from '../../converter/ShortDateConverter';
import HSelectOneRadio from '../../jsf/components/HSelectOneRadio';

export default class PassengerForm extends React.Component {
  static propTypes = {
    selectedFlight: PropTypes.instanceOf(Flight).isRequired,
    cancel: PropTypes.func.isRequired,
    back: PropTypes.func.isRequired,
    bookingFormData: PropTypes.object.isRequired,
  };

  updateSlider = function() {
    let currentValue = this.bookingForm.state.data.passengerCount;
    let maxValue = this.props.selectedFlight.aircraft.passengerCount;
    let minValue = 1;
    if (minValue <= currentValue && currentValue <= maxValue) {
      if (this.sliderChange) {
        this.sliderChange = false;
      } else {
        // to avoid a loop only change when changed through direct input
        this.slider.slider('value', currentValue);
      }
      // Validierungsmeldung ausknipsen (falls vorhanden)
      this.passengerCountOutput.setState({
        hasError: false,
      });
    }
  };

  constructor(props, context) {
    super(props, context);

    this.state = {
      passengerFormVisible: true,
      bookingDetailsVisible: false,
      data: this.props.bookingFormData,
      forceEdit: false,
      existingUser: false,
      currentPassengerIndex: 0,
    };

    // TODO create empty passengers

    this.validateForm = this.validateForm.bind(this);
    this.setPassportHelp = this.setPassportHelp.bind(this);
    this.passportIdListener = this.passportIdListener.bind(this);
    this.next = this.next.bind(this);
    this.back = this.back.bind(this);
    this.toggleForceEdit = this.toggleForceEdit.bind(this);
  }

  next() {
    this.state = {
      passengerFormVisible: false,
      bookingDetailsVisible: true,
    };
  }

  back() {
    this.state = {
      passengerFormVisible: true,
      bookingDetailsVisible: false,
    };
  }

  toggleForceEdit() {
    this.setState({
      forceEdit: !this.state.forceEdit,
    });
  }

  validateForm() {

  }

  setPassportHelp() {

  }

  /**
   *
   * @param {React.Component} input
   * @param {string} render
   */
  passportIdListener(input, render) {

  }

  render() {
    if (this.state.passengerFormVisible) {
      return (
          <HForm ref={(form) => {
            this.bookingForm = form;
          }} id="passengerData" styleClass="ice-skin-rime">
            <div className="inputFieldGroup">
              <span
                  className="iceOutTxt headerLabel">Enter Data for Passenger #{this.state.currentPassengerIndex +
              1}</span>
            </div>
            // TODO
            <f:event id="multiFieldValidationEvent"
                     listener="#{passengerFormBean.validateForm}"
                     type="postValidate"/>
            <HPanelGroup id="passportContainer" layout="block"
                         styleClass="contentLevelContainer blockArea">
              <div className="lFloat indented inputFieldGroup">
                <CHhoose>
                  <CWhen
                      test={this.props.selectedFlight.foreignTravel}>
                    <span className="iceOutTxt masInfoFieldLabel minindented">Passport Number:</span>
                    <HInputText id="passportNumberInput" maxlength={6}
                                value="currentPassenger.passportNumber"
                                required="true"
                                requiredMessage="Insert your Passport Number">
                      <FAjax event="blur"
                             listener={this.passportIdListener}
                             execute="@this"
                             render="@form"/>
                    </HInputText>
                  </CWhen>
                  <COtherwise>
                    <span className="iceOutTxt masInfoFieldLabel minindented">Id Card Number:</span>
                    <HInputText id="idCardNumberInput" maxlength={5}
                                value="currentPassenger.idCardNumber"
                                required="true"
                                requiredMessage="Insert your Id Card Number">
                      <FAjax event="blur"
                             listener={this.passportIdListener}
                             execute="@this"
                             render="@form"/>
                    </HInputText>
                  </COtherwise>
                </CHhoose>
                <HGraphicImage id="helpIcon" library="images"
                               name="icon_info.gif">
                  <FAjax render="@all" event="click"
                         listener={this.setPassportHelp}/>
                </HGraphicImage>
              </div>

              <div className="clear"/>
            </HPanelGroup>
            <HPanelGroup id="personalDataContainer" layout="block"
                         styleClass="contentLevelContainer blockArea">
              <CIf test={this.state.existingUser}>
                <div className="indented inputFieldGroup">
                  <HCommandButton id="forceEditButton" value="Edit Data"
                                  styleClass="iceCmdBtn btnOption"
                                  action={this.toggleForceEdit}>
                  </HCommandButton>
                </div>
              </CIf>
              <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Firstname:</span>
                <HInputText id="firstNameInput"
                            disabled={this.state.existingUser &&
                            !this.state.forceEdit}
                            value="currentPassenger.firstName"
                            required="true"
                            requiredMessage="Insert your Firstname"/>
              </div>
              <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Lastname:</span>
                <HInputText id="lastNameInput"
                            disabled={this.state.existingUser &&
                            !this.state.forceEdit}
                            value="currentPassenger.lastName"
                            required="true"
                            requiredMessage="Insert your Lastname"/>
              </div>
              <div className="lFloat indented inputFieldGroup">
                <span
                    className="iceOutTxt masInfoFieldLabel minindented">Birthdate:</span>
                <HInputText id="birthDateInput"
                            disabled={this.state.existingUser &&
                            !this.state.forceEdit}
                            value="currentPassenger.birthDay"
                            required="true"
                            requiredMessage="Insert your Birthdate"
                            converter={ShortDateConverter}/>
              </div>
              <div className="clear"/>
            </HPanelGroup>
            <HPanelGroup id="luggageContainer" layout="block"
                         styleClass="contentLevelContainer blockArea">
              <span className="iceOutTxt masInfoFieldLabel minindented">Select the desired amount of luggage</span>
              <HSelectOneRadio id="luggageRadio"
                               styleClass="iceSelOneRb masInfoInputField"
                               required="true"
                               layout="pageDirection"
                               requiredMessage="Select the amount of luggage you want to check in"
                               value="currentPassenger.luggageCount">
                <FSelectItems id="luggageNumbers"
                              value="#{passengerFormBean.luggageItems}"/>
              </HSelectOneRadio>
              <div className="clear"/>
              <HMessage styleClass="iceMsgError inputFieldLabel"
                        for="firstNameInput" id="firstNameErrorMessage"/>
              <HMessage styleClass="iceMsgError inputFieldLabel"
                        for="lastNameInput" id="lastNameErrorMessage"/>
              <HMessage styleClass="iceMsgError inputFieldLabel"
                        for="birthDateInput" id="birthDateErrorMessage"/>
              <HMessage styleClass="iceMsgError inputFieldLabel"
                        for="idCardNumberInput" id="idCardErrorMessage"/>
              <HMessage styleClass="iceMsgError inputFieldLabel"
                        for="passportNumberInput" id="passportErrorMessage"/>
            </HPanelGroup>

            <HCommandButton value="Cancel"
                            action={this.props.cancel}
                            id="cancelBookingButton"
                            styleClass="iceCmdBtn btnOption"/>
            <HCommandButton immediate="true" action={this.back}
                            value="Back"
                            id="backButton"
                            styleClass="iceCmdBtn btnOption"/>
            <HCommandButton value="Continue"
                            id="continueButton"
                            action={this.next}
                            styleClass="iceCmdBtn btnOption"/>

            // TODO
            <ice:panelPopup id="passportHelpPopup"
                            visible="#{passengerFormBean.passportHelp}"
                            draggable="false"
                            styleClass="popup frameHolder" autoCentre="true">
              <FFacet name="body">
                <div id="iFrameWrapper">
                  <ICEOutputText styleClass="iceOutTxt">
                    Your passport number should start with P and constist of 5
                    numbers <br/>
                    Your id card number should consist of 5 numbers
                  </ICEOutputText>
                </div>
              </FFacet>
            </ice:panelPopup>
          </HForm>
      );
    } else {
      return <div></div>;
    }
  }
}
