// src/main/webapp/angular/app/components/includes/version-annotation/version-annotation.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-version-annotation',
  templateUrl: './version-annotation.component.html',
  styleUrls: ['./version-annotation.component.css'],
})
export class VersionAnnotationComponent {

  constructor() {
  }
}

<h4>Master Prototype Angular Version</h4>
<ice-output-link styleClass="ice-linkbutton" type="text/html"
                 value="https://github.com/denny99/master-prototype/tree/angular">
    Github Repo
</ice-output-link>

// src/main/webapp/react/components/includes/VersionAnnotation.js
import React from 'react';
import {IceOutputLink} from 'react-jsf';

export default class VersionAnnotation extends React.Component {
  render() {
    return (
        <React.Fragment>
          <h4>Master Prototype React Version</h4>
          <IceOutputLink styleClass="ice-linkbutton" type="text/html"
                         value="https://github.com/denny99/master-prototype/tree/react">
            Github Repo
          </IceOutputLink>
        </React.Fragment>
    );
  }
}
