// src/main/webapp/angular/app/components/pages/booking-success/booking-success.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'booking-success',
  templateUrl: './booking-success.component.html',
  styleUrls: ['./booking-success.component.css'],
})
export class BookingSuccessComponent {

  constructor() {
  }
}

<h-body>
    <app-base-template>
        <ui-define name="content">
            <h2 id="bookingCompleteMessage">Booking Successful!</h2>
            <h-form id="successInfo">
                <h-command-button id="completeButton" action="/pages/flightOverview"
                                  value="Back to Flights"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>
            </h-form>
        </ui-define>
    </app-base-template>
</h-body>

// src/main/webapp/react/components/pages/BookingSuccess.js
import React from 'react';
import PropTypes from 'prop-types';
import {HCommandButton, HForm, UiDefine} from 'react-jsf';
import BaseTemplate from '../template/BaseTemplate';

export default class BookingSuccess extends React.Component {
  static propTypes = {
    finish: PropTypes.func.isRequired,
  };

  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
        <BaseTemplate>
          <UiDefine name='content'>
            <h2 key={0} id="bookingCompleteMessage">Booking Successful!</h2>
            <HForm key={1} id="successInfo">
              <HCommandButton id="completeButton" action={this.props.finish}
                              value="Back to Flights"
                              styleClass="iceCmdBtn btnOption"/>
            </HForm>
          </UiDefine>
        </BaseTemplate>
    );
  }
}
