// src/main/webapp/angular/app/components/pages/booking-form/booking-form.component.ts
import {AfterViewInit, Component, ViewChild} from '@angular/core';
import {Router} from '@angular/router';
import {IntegerPipe} from '../../../converter/integer-pipe';
import Flight from '../../../entity/Flight';
import {ConversationService, HInputTextComponent, JsfInput, ValidationResponse} from 'angular-jsf-components';
import {AjaxService} from '../../../services/ajax.service';

declare let $: any;

@Component({
    selector: 'app-booking-form',
    templateUrl: './booking-form.component.html',
    styleUrls: ['./booking-form.component.css'],
})
export class BookingFormComponent implements AfterViewInit {
    private integerConverter = new IntegerPipe();
    // it is not possible to annotate this properly with the jqueryui types
    private slider: any;

    @ViewChild('passengerCountOutput')
    private passengerCountOutput: HInputTextComponent;

    constructor(private ajaxService: AjaxService,
                private router: Router,
                private conversationService: ConversationService) {
        if (!this.conversationService.isActive()) {
            console.error('attempted to visit site without selecting a flight');
            router.navigateByUrl('pages/flightOverview').then().catch((e) => {
                console.error(e);
            });
        }

        // this function is used inside of the input field
        this.validatePassengerCount = this.validatePassengerCount.bind(this);
    }

    get passengerCount(): number {
        return this.conversationService.conversation.getProperty(
            'passengerCount') || 1;
    }

    set passengerCount(val: number) {
        this.conversationService.conversation.setProperty(
            'passengerCount', val);
    }

    get maxPassengers(): number {
        return this.selectedFlight.aircraft.passengerCount;
    }

    get travelInsurance(): boolean {
        return this.conversationService.conversation.getProperty(
            'travelInsurance') || false;
    }

    set travelInsurance(val: boolean) {
        this.conversationService.conversation.setProperty(
            'travelInsurance', val);
    }

    get selectedFlight(): Flight {
        return this.conversationService.conversation.getProperty(
            'selectedFlight');
    }

    ngAfterViewInit() {
        this.slider = $('#passengerCountSlider').slider({
            max: this.maxPassengers,
            value: this.passengerCount,
            change: (event, ui) => {
                this.passengerCount = ui.value;
            },
        });
    }

    async updateSlider(): Promise<void> {
        const currentValue = this.passengerCount;
        const maxValue = this.maxPassengers;
        const minValue = 1;
        if (minValue <= currentValue && currentValue <= maxValue) {
            // to avoid a loop only change when changed through direct input
            this.slider.slider('value', currentValue);
            try {
                await this.passengerCountOutput.validate();
            } catch (e) {
                console.error(e);
            }
        }
    }

    /**
     * validates the entered amount of passengers
     * @param {JsfInput} element
     * @returns {Promise<ValidationResponse>}
     */
    async validatePassengerCount(element: JsfInput): Promise<ValidationResponse> {
        // input validates itself after init, so ref is not set use 1 as default value
        return this.ajaxService.validatePassengerCount(
            this.selectedFlight, element.value);
    }

    async createPassengers(): Promise<void> {
        try {
            // save date in conversation
            this.conversationService.conversation.setProperty('passengerCount',
                this.passengerCount);
            this.conversationService.conversation.setProperty('travelInsurance',
                this.travelInsurance);
            await this.router.navigateByUrl('pages/passengerForm');
        } catch (e) {
            console.error(e);
        }
    }

    async cancelBooking() {
        try {
            // save date in conversation
            this.conversationService.endConversation();
            await this.router.navigateByUrl('pages/flightOverview');
        } catch (e) {
            console.error(e);
        }
    }
}

<h-body>
    <h-form id="bookingData" styleClass="ice-skin-rime">
        <!-- display flight data -->
        <cc-flight-details [headline]="true" [standalone]="false"
                           [flight]="selectedFlight"></cc-flight-details>

        <!-- select number of passengers slider -->
        <h-panel-group id="basicData" layout="block"
                       styleClass="contentLevelContainer blockArea">
            <div class="inputFieldGroup">
                <span class="iceOutTxt headerLabel">Basic Data</span>
            </div>
            <h-panel-group layout="block" id="sliderGroup"
                           styleClass="indented topMargin">
                <div class="inputFieldGroup center" style="width: 450px;">
                    <span class="iceOutTxt iceOutLbl ssLabel">Select desired amount of passengers</span>
                </div>
                <div id="passengerContainer" class="blockArea">
                    <div class="inputFieldGroup" id="passengerAmountContainer">
                        <ice-panel-group id="passengerTooltipBubble"
                                         panelTooltip="passengerTooltip"
                                         [style]="{position: 'relative', top: '-15px'}"
                                         styleClass="infoBubble">
                            <f-facet name="tooltip">
                                <div>
                                    <span class="iceOutTxt">Use the slider or the input to set the amount of passengers</span>
                                </div>
                            </f-facet>
                        </ice-panel-group>
                        <div class="clear"></div>
                        <div id="sliderDiv" class="inputFieldGroup center">
                            <div class="inputFieldGroup center" style="*margin-top:-15px;">
                                <h-input-text #passengerCountOutput
                                              [(ngModel)]="passengerCount"
                                              id="passengerCountOutput"
                                              [style]="{'color': '#003B78 !important', 'text-align': 'center'}"
                                              (onchange)="updateSlider($event);"
                                              [validator]="validatePassengerCount"
                                              [converter]="integerConverter"
                                              converterMessage="Enter only Numbers">
                                    <!--This call did not do anything relevant for the ui-->
                                    <!--<f-ajax event="blur" execute="@this" render="costMsg"-->
                                    <!--(listener)="costsListener($event)"></f-ajax>-->
                                </h-input-text>
                                <span style="*margin-left: 4px;"># Passengers</span>
                            </div>
                            <div style="position: relative; bottom: 0px;">
                                <div id="slider_div">
                                    <div id="passengerCountSlider"
                                         style="position:relative;top:6px;width:133px;">
                                        <img id="sliderImage" src="/resources/images/bar150.gif"
                                             width="150"
                                             height="12"
                                             alt="" class="sliderImg"/>
                                    </div>
                                </div>
                                <ice-output-text id="costs"
                                                 value="Costs p.P. {{selectedFlight.costs}}"
                                                 styleClass="iceOutTxt ssInfoFieldLabel2">
                                    <!--Does not work here value is a string not, would work as pipe in the {{}} -->
                                    <!--<f-convert-number pattern="##,###" [groupingUsed]="true"-->
                                    <!--locale="de-DE"></f-convert-number>-->
                                </ice-output-text>
                                <span>&euro;</span>
                            </div>

                            <h-input-hidden id="maxSliderTickHidden"
                                            [(ngModel)]="maxPassengers"></h-input-hidden>
                        </div>
                    </div>
                </div>
            </h-panel-group>
        </h-panel-group>
        <h-message id="costMsg"
                   style="{'width':'404px', 'text-align':'center'}"
                   styleClass="iceMsgError inputFieldLabel minindented"
                   for="passengerCountOutput"></h-message>

        <!-- checkbox for insurance -->
        <h-panel-group layout="block"
                       styleClass="contentLevelContainer blockArea">
            <div class="indented inputFieldGroup" style="margin-top: 5px;">
                <h-select-boolean-checkbox id="insuranceCB"
                                           [(ngModel)]="travelInsurance">
                </h-select-boolean-checkbox>
                <h-output-label id="insuranceLabel" for="insuranceCB"
                                [style]="{position:'relative', top: '-2px'}"
                                styleClass="InfoFieldLabel minindented">
                    Reisezusatzversicherung buchen
                </h-output-label>
                <div class="clear"></div>
            </div>
        </h-panel-group>
        <h-command-button value="Cancel"
                          (action)="cancelBooking()"
                          id="cancelBookingButton"
                          styleClass="iceCmdBtn btnOption"></h-command-button>
        <h-command-button id="continueButton" value="Continue"
                          (action)="createPassengers()"
                          styleClass="iceCmdBtn btnOption"></h-command-button>
    </h-form>
</h-body>

// src/main/webapp/react/components/pages/BookingForm.js
import React from 'react';
import PropTypes from 'prop-types';
import CCFlightDetails from '../cc/CCFlightDetails';
import Flight from '../../entity/Flight';
import {
  FFacet, HCommandButton, HForm, HInputHidden, HInputText, HMessage,
  HOutputLabel, HPanelGroup, HSelectBooleanCheckbox, IceOutputText,
  IcePanelGroup, IcePanelTooltip, UiDefine, ValidationResponse,
} from 'react-jsf';
import IntegerConverter from '../../converter/IntegerConverter';
import PassengerForm from './PassengerForm';
import AjaxService from '../../service/AjaxService';
import BaseTemplate from '../template/BaseTemplate';

export default class BookingForm extends React.Component {
  static propTypes = {
    selectedFlight: PropTypes.instanceOf(Flight).isRequired,
    cancel: PropTypes.func.isRequired,
  };

  updateSlider() {
    let currentValue = this.bookingForm.state.data.passengerCount;
    let maxValue = this.props.selectedFlight.aircraft.passengerCount;
    let minValue = 1;
    if (minValue <= currentValue && currentValue <= maxValue) {
      if (this.sliderChange) {
        this.sliderChange = false;
      } else {
        // to avoid a loop only change when changed through direct input
        this.slider.slider('value', currentValue);
      }
    }
  };

  constructor(props, context) {
    super(props, context);

    this.state = {
      bookingFormVisible: true,
      passengerFormVisible: false,
      data: {
        passengerCount: 1,
      },
    };

    this.validatePassengerCount = this.validatePassengerCount.bind(this);
    this.showPassengerForm = this.showPassengerForm.bind(this);
    this.hidePassengerForm = this.hidePassengerForm.bind(this);
    this.updateSlider = this.updateSlider.bind(this);
  }

  showPassengerForm() {
    this.setState({
      bookingFormVisible: false,
      passengerFormVisible: true,
    });
  }

  hidePassengerForm() {
    this.setState({
      bookingFormVisible: true,
      passengerFormVisible: false,
    });
  }

  /**
   * validates the entered amount of passengers
   * @return {Promise<ValidationResponse>}
   */
  async validatePassengerCount() {
    // input validates itself after init, so ref is not set use 1 as default value
    return AjaxService.validatePassengerCount(this.props.selectedFlight,
        this.bookingForm ? this.bookingForm.state.data.passengerCount : 1);
  }

  componentDidMount() {
    this.sliderChange = false;
    this.slider = $('#passengerCountSlider').slider({
      max: this.props.selectedFlight.aircraft.passengerCount,
      value: this.bookingForm.state.data.passengerCount,
      change: async (event, ui) => {
        this.bookingForm.state.data.passengerCount = ui.value;
        this.sliderChange = true;
        // Validierungsmeldung ausknipsen (falls vorhanden)
        await this.passengerCountOutput.validate();
        this.passengerCountOutput.handleChange({
          target: ui,
        });
      },
    });
  }

  componentDidUpdate() {
    // reapply slider if necessary
    if (this.state.bookingFormVisible) {
      this.componentDidMount();
    }
  }

  render() {
    if (this.state.bookingFormVisible) {
      return (
          <BaseTemplate>
            <UiDefine name='content'>
              <HForm ref={(form) => {
                this.bookingForm = form;
              }} id="bookingData" data={this.state.data}
                     styleClass="ice-skin-rime">
                <CCFlightDetails headline={true} standalone={false}
                                 flight={this.props.selectedFlight}/>
                <HPanelGroup id="basicData" layout="block"
                             styleClass="contentLevelContainer blockArea">
                  <div className="inputFieldGroup">
                    <span className="iceOutTxt headerLabel">Basic Data</span>
                  </div>
                  <HPanelGroup layout="block" id="sliderGroup"
                               styleClass="indented topMargin">
                    <div className="inputFieldGroup center"
                         style={{width: '450px'}}>
                      <span className="iceOutTxt iceOutLbl ssLabel">Select desired amount of passengers</span>
                    </div>
                    <div id="passengerContainer" className="blockArea">
                      <div className="inputFieldGroup"
                           id="passengerAmountContainer">
                        <IcePanelGroup id="passengerTooltipBubble"
                                       panelTooltip="passengerTooltip"
                                       style={{
                                         position: 'relative',
                                         top: '-15px',
                                       }}
                                       styleClass="infoBubble"/>
                        <div className="clear"/>
                        <div id="sliderDiv" className="inputFieldGroup center">
                          <div className="inputFieldGroup center"
                               style={{marginTop: '-15px'}}>
                            <HInputText ref={(input) => {
                              this.passengerCountOutput = input;
                            }} value="passengerCount"
                                        id="passengerCountOutput"
                                        style={{
                                          color: '#003B78 !important',
                                          textAlign: 'center',
                                        }}
                                        onchange={this.updateSlider}
                                        validator={this.validatePassengerCount}
                                        converter={IntegerConverter}
                                        converterMessage="Enter only Numbers"/>
                            <span
                                style={{marginLeft: '4px'}}># Passengers</span>
                          </div>
                          <div style={{position: 'relative', bottom: '0px'}}>
                            <div id="slider_div">
                              <div id="passengerCountSlider"
                                   style={{
                                     position: 'relative',
                                     top: '6px',
                                     width: '133px',
                                   }}>
                                <img id="sliderImage"
                                     src="/resources/images/bar150.gif"
                                     width="150"
                                     height="12"
                                     alt="" className="sliderImg"/>
                              </div>
                            </div>

                            <IceOutputText id="costs"
                                           styleClass="ssInfoFieldLabel2">
                              Costs p.P. {this.props.selectedFlight.costs}
                            </IceOutputText>
                            <span>€</span>
                          </div>

                          <HInputHidden id="maxSliderTickHidden"
                                        value={this.props.selectedFlight.aircraft.passengerCount}/>
                        </div>
                      </div>
                    </div>

                    <IcePanelTooltip id="passengerTooltip" hideOn="mouseout">
                      <FFacet name="body">
                        <div>
                          <span className="iceOutTxt">Use the slider or the input to set the amount of passengers</span>
                        </div>
                      </FFacet>
                    </IcePanelTooltip>
                  </HPanelGroup>
                </HPanelGroup>
                <HMessage id="costMsg"
                          style={{width: '404px', textAlign: 'center'}}
                          styleClass="iceMsgError inputFieldLabel minindented"
                          for="passengerCountOutput"/>

                <HPanelGroup layout="block"
                             styleClass="contentLevelContainer blockArea">
                  <div className="indented inputFieldGroup"
                       style={{marginTop: '5px'}}>
                    <HSelectBooleanCheckbox id="insuranceCB"
                                            value="travelInsurance">
                    </HSelectBooleanCheckbox>
                    <HOutputLabel id="insuranceLabel" for="insuranceCB"
                                  style={{position: 'relative', top: '-2px'}}
                                  styleClass="InfoFieldLabel minindented">Travel
                      Insurance
                    </HOutputLabel>
                    <div className="clear"/>
                  </div>
                </HPanelGroup>
                <HCommandButton value="Cancel"
                                action={this.props.cancel}
                                immediate={true}
                                id="cancelBookingButton"
                                styleClass="iceCmdBtn btnOption"/>
                <HCommandButton id="continueButton" value="Continue"
                                action={this.showPassengerForm}
                                styleClass="iceCmdBtn btnOption"/>
              </HForm>
            </UiDefine>
          </BaseTemplate>
      );
    } else {
      return <PassengerForm selectedFlight={this.props.selectedFlight}
                            cancel={this.props.cancel}
                            back={this.hidePassengerForm}
                            bookingFormData={this.bookingForm.state.data}/>;
    }
  }
}
