// src/main/webapp/resources/js/react/jsf/components/datatable/Paginator.js
import React from 'react';
import PropTypes from 'prop-types';

export default class Paginator extends React.Component {
  static propTypes = {
    currentPage: PropTypes.number,
    pageSize: PropTypes.number,
    maxResults: PropTypes.number,
    top: PropTypes.bool,
  };

  render() {
    const maxPage = Math.ceil(this.props.maxResults / this.props.pageSize);
    let firstLink = this.props.currentPage === 1 ?
        <span id="yui-pg0-0-first-span"
              className="ui-paginator-first ui-state-default ui-corner-all ui-state-disabled">
            <span className="ui-icon ui-icon-seek-first">First</span>
          </span> :
        <a id="yui-pg1-0-first-link" href="#" onClick={this.context.first}
           className="ui-paginator-first ui-state-default ui-corner-all"><span
            className="ui-icon ui-icon-seek-first">First</span></a>;
    let prevLink = this.props.currentPage === 1 ?
        <span id="yui-pg0-0-prev-span"
              className="ui-paginator-previous ui-state-default ui-corner-all ui-state-disabled">
            <span className="ui-icon ui-icon-seek-prev">Prev</span>
          </span> :
        <a id="yui-pg1-0-prev-link" href="#" onClick={this.context.prev}
           className="ui-paginator-previous ui-state-default ui-corner-all"><span
            className="ui-icon ui-icon-seek-prev">Prev</span></a>;
    let nextLink = this.props.currentPage === maxPage ?
        <span id="yui-pg2-0-next-span"
              className="ui-paginator-next ui-state-default ui-corner-all ui-state-disabled"><span
            className="ui-icon ui-icon-seek-next">Next</span></span> :
        <a id="yui-pg0-0-next-link" href="#" onClick={this.context.next}
           className="ui-paginator-next ui-state-default ui-corner-all">
          <span className="ui-icon ui-icon-seek-next">Next</span>
        </a>;
    let lastLink = this.props.currentPage === maxPage ?
        <span id="yui-pg2-0-last-span"
              className="ui-paginator-last ui-state-default ui-corner-all ui-state-disabled"><span
            className="ui-icon ui-icon-seek-end">Last</span></span> :
        <a id="yui-pg0-0-last-link" href="#" onClick={this.context.last}
           className="ui-paginator-last ui-state-default ui-corner-all">
          <span className="ui-icon ui-icon-seek-end">Last</span>
        </a>;
    let pageLinks = [];
    for (let i = Math.max(1, this.props.currentPage -
        (this.props.currentPage === maxPage ? 9 : 5)), j = Math.min(maxPage,
        this.props.currentPage < 7 ? 10 : (this.props.currentPage + 4)); i <=
         j; i++) {
      if (i === this.props.currentPage) {
        pageLinks.push(<span key={i}
                             className="ui-paginator-page ui-state-default ui-corner-all ui-paginator-current-page ui-state-active">{i}</span>);
      } else {
        pageLinks.push(<a href="#" onClick={() => {
          this.context.setPage(i);
        }}
                          className="ui-paginator-page ui-state-default ui-corner-all"
                          key={i}>{i}</a>);
      }
    }

    return (
        <div
            className={`ui-paginator ${this.props.top ?
                'ui-paginator-top' :
                'ui-paginator-bottom'} ui-widget-header ui-corner-tl ui-corner-tr`}
            id={`datatableForm:flightsTable_paginator${this.props.top ?
                'top' :
                'bottom'}`}>
          {firstLink}
          {prevLink}
          <span id="yui-pg0-0-pages" className="ui-paginator-pages">
            {pageLinks}
          </span>
          {nextLink}
          {lastLink}
        </div>
    );
  }
}

Paginator.contextTypes = {
  first: PropTypes.func,
  prev: PropTypes.func,
  next: PropTypes.func,
  last: PropTypes.func,
  setPage: PropTypes.func,
};

// src/main/webapp/angular/app/jsf/components/datatable/paginator/paginator.component.ts
import {
  Component, EventEmitter, Input, OnChanges,
  Output,
} from '@angular/core';

@Component({
  selector: 'ace-data-table-paginator',
  templateUrl: './paginator.component.html',
  styleUrls: ['./paginator.component.css'],
})
export class PaginatorComponent implements OnChanges {
  @Input()
  currentPage: number;
  @Input()
  pageSize: number;
  @Input()
  maxResults: number;
  @Input()
  top: boolean;
  @Input()
  parentId: string;
  @Output()
  newPage = new EventEmitter<number>();

  private maxPage: number;
  private pageLinks: Array<number>;

  constructor() {
  }

  ngOnChanges(): void {
    this.maxPage = Math.ceil(this.maxResults / this.pageSize);
    this.pageLinks = [];
    const startPage = Math.max(1, this.currentPage -
        (this.currentPage + 5 > this.maxPage ?
            9 - (this.maxPage - this.currentPage) : 5));
    const endPage = Math.min(this.maxPage,
        this.currentPage < 7 ? 10 : (this.currentPage + 4));

    for (let i = startPage, j = endPage; i <=
    j; i++) {
      this.pageLinks.push(i);
    }
  }

  setPage(e: Event, i: number): void {
    e.preventDefault();
    this.newPage.emit(i);
  }
}

<div
    [class]="'ui-paginator ' + (top ?'ui-paginator-top' : 'ui-paginator-bottom') + ' ui-widget-header ui-corner-tl ui-corner-tr'"
    [id]="parentId + '_paginator' + (top ? 'top' : 'bottom')">
  <span *ngIf="currentPage === 1" id="yui-pg0-0-first-span"
        class="ui-paginator-first ui-state-default ui-corner-all ui-state-disabled">
    <span class="ui-icon ui-icon-seek-first">First</span>
  </span>
  <a *ngIf="currentPage !== 1" id="yui-pg1-0-first-link"
     (click)="setPage($event, 1)"
     class="ui-paginator-first ui-state-default ui-corner-all">
    <span class="ui-icon ui-icon-seek-first">First</span>
  </a>


  <span *ngIf="currentPage === 1" id="yui-pg0-0-prev-span"
        class="ui-paginator-previous ui-state-default ui-corner-all ui-state-disabled">
    <span class="ui-icon ui-icon-seek-prev">Prev</span>
  </span>
  <a *ngIf="currentPage !== 1" id="yui-pg1-0-prev-link"
     (click)="setPage($event, currentPage - 1)"
     class="ui-paginator-previous ui-state-default ui-corner-all">
    <span class="ui-icon ui-icon-seek-prev">Prev</span>
  </a>
  <span id="yui-pg0-0-pages" class="ui-paginator-pages">
    <ng-container *ngFor="let i of pageLinks">
      <span *ngIf="i === currentPage"
            class="ui-paginator-page ui-state-default ui-corner-all ui-paginator-current-page ui-state-active">{{i}}</span>
      <a *ngIf="i !== currentPage" (click)="setPage($event, i)"
         class="ui-paginator-page ui-state-default ui-corner-all">{{i}}</a>
    </ng-container>
  </span>
  <span *ngIf="currentPage === maxPage" id="yui-pg2-0-next-span"
        class="ui-paginator-next ui-state-default ui-corner-all ui-state-disabled">
    <span class="ui-icon ui-icon-seek-next">Next</span>
  </span>
  <a *ngIf="currentPage !== maxPage" id="yui-pg0-0-next-link"
     (click)="setPage($event, currentPage + 1)"
     class="ui-paginator-next ui-state-default ui-corner-all">
    <span class="ui-icon ui-icon-seek-next">Next</span>
  </a>

  <span *ngIf="currentPage === maxPage" id="yui-pg2-0-last-span"
        class="ui-paginator-last ui-state-default ui-corner-all ui-state-disabled">
    <span class="ui-icon ui-icon-seek-end">Last</span>
  </span>
  <a *ngIf="currentPage !== maxPage" id="yui-pg0-0-last-link"
     (click)="setPage($event, maxPage)"
     class="ui-paginator-last ui-state-default ui-corner-all">
    <span class="ui-icon ui-icon-seek-end">Last</span>
  </a>
</div>
