// src/main/webapp/react/components/pages/BookingDetails.js
import React from 'react';
import PropTypes from 'prop-types';
import CCFlightDetails from '../cc/CCFlightDetails';
import Flight from '../../entity/Flight';
import HPanelGroup from '../../jsf/components/HPanelGroup';
import HOutputText from '../../jsf/components/HOutputText';
import FConvertNumber from '../../jsf/components/FConvertNumber';
import HCommandButton from '../../jsf/components/HCommandButton';
import HOutputLabel from '../../jsf/components/HOutputLabel';
import HMessage from '../../jsf/components/HMessage';
import HForm from '../../jsf/components/HForm';
import IceSelectBooleanCheckbox from '../../jsf/components/IceSelectBooleanCheckbox';
import AceDialog from '../../jsf/components/AceDialog';
import IceCommandButton from '../../jsf/components/IceCommandButton';
import BookingSuccess from './BookingSuccess';
import CChoose from '../../jsf/components/CChoose';
import CWhen from '../../jsf/components/CWhen';
import COtherwise from '../../jsf/components/COtherwise';
import UiRepeat from '../../jsf/components/UiRepeat';
import ShortDateConverter from '../../converter/ShortDateConverter';

export default class BookingDetails extends React.Component {
  static propTypes = {
    back: PropTypes.func.isRequired,
    cancel: PropTypes.func.isRequired,
    selectedFlight: PropTypes.instanceOf(Flight).isRequired,
    data: PropTypes.object,
  };

  constructor(props, context) {
    super(props, context);

    this.state = {
      showInfo: false,
      bookingDetailsVisible: true,
      bookingSuccessVisible: false,
    };

    this.confirmBooking = this.confirmBooking.bind(this);
    this.finishBooking = this.finishBooking.bind(this);
    this.validateTac = this.validateTac.bind(this);
  }

  /**
   * ensure checkbox is set
   * @return {{error: boolean}}
   */
  validateTac(input) {
    return {
      error: !input.value,
      message: 'You have to accept the TAC',
    };
  }

  finishBooking() {
    // POST to backend
    this.setState({
      bookingDetailsVisible: false,
      bookingSuccessVisible: true,
    });
  }

  confirmBooking() {
    if (this.detailsForm.hasError()) {
      return;
    }

    this.setState({
      showInfo: true,
    });
  }

  render() {
    if (this.state.bookingDetailsVisible) {
      return (
          <React.Fragment>
            <h2>Booking Overview</h2>
            <HForm id="bookingDetails" data={this.props.data}
                   ref={(form) => this.detailsForm = form}>
              <CCFlightDetails headline={true} standalone={false}
                               flight={this.props.selectedFlight}/>

              <HPanelGroup layout="block"
                           styleClass="contentLevelContainer blockArea">
                <div className="inputFieldGroup">
                  <span className="iceOutTxt headerLabel">Basic Data</span>
                </div>
                <HPanelGroup layout="block">
                  <div className="clear" style={{height: '6px'}}/>
                  <div className="inputFieldGroup minindented">
                        <span className="iceOutTxt kdInputFieldLabel"
                              style={{width: '200px'}}>Passenger Count:</span>
                    <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                 value={this.props.data.passengerCount}/>
                    <span className="iceOutTxt kdInputFieldLabel"
                          style={{width: '200px'}}>Flight Costs:</span>
                    <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                 value={this.props.data.passengerCount *
                                 this.props.selectedFlight.costs}>
                      <FConvertNumber pattern="###,##" groupingUsed={true}
                                      locale="de"/>
                    </HOutputText>
                    <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                 rendered={this.props.data.travelInsurance}
                                 value="Travel Insurance"
                    />
                  </div>
                </HPanelGroup>
              </HPanelGroup>
              <HPanelGroup layout="block"
                           styleClass="contentLevelContainer blockArea">
                <div className="inputFieldGroup">
                  <span className="iceOutTxt headerLabel">Passenger Data</span>
                </div>
                <UiRepeat value={this.props.data.passengers} var="passenger">
                  <HPanelGroup layout="block">
                    <div className="clear" style={{height: '6px'}}/>
                    <div className="inputFieldGroup minindented">
                      <CChoose>
                        <CWhen test={this.props.selectedFlight.foreignTravel()}>
                          <span className="iceOutTxt kdInputFieldLabel"
                                style={{width: '200px'}}>Passenger Passport:</span>
                          <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                       value="#[passenger.passportNumber]"/>
                        </CWhen>
                        <COtherwise>
                          <span className="iceOutTxt kdInputFieldLabel"
                                style={{width: '200px'}}>Passenger Id Card:</span>
                          <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                       value="#[passenger.idCardNumber]"/>
                        </COtherwise>
                      </CChoose>
                      <span className="iceOutTxt kdInputFieldLabel"
                            style={{width: '200px'}}>Passenger Firstname:</span>
                      <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                   value="#[passenger.firstName]"/>
                      <span className="iceOutTxt kdInputFieldLabel"
                            style={{width: '200px'}}>Passenger Lastname:</span>
                      <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                   value="#[passenger.lastName]"/>
                      <span className="iceOutTxt kdInputFieldLabel"
                            style={{width: '200px'}}>Passenger Birthdate:</span>
                      <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                   value="#[passenger.birthDay]"
                                   converter={ShortDateConverter}/>
                      <span className="iceOutTxt kdInputFieldLabel"
                            style={{width: '200px'}}>Passenger # Luggage:</span>
                      <HOutputText styleClass="iceOutTxt kdInputFieldLabel"
                                   value="#[passenger.luggageCount]"/>
                    </div>
                  </HPanelGroup>
                </UiRepeat>
              </HPanelGroup>

              <HPanelGroup layout="block"
                           styleClass="contentLevelContainer blockArea">
                <HPanelGroup id="tacDiv">
                  <IceSelectBooleanCheckbox id="tacCheckbox" value="tac"
                                            validator={this.validateTac}/>
                  <HOutputLabel id="tacCheckboxLabel" for="tacCheckbox">Accept
                    TAC</HOutputLabel>

                  <HMessage styleClass="iceMsgError inputFieldLabel"
                            for="tacCheckbox" id="tacErrorMessage"/>
                </HPanelGroup>
                {/*// TODO*/}
                {/*<ace:tooltip id="tacTooltip" for="tacDiv"*/}
                {/*speechBubble={false} showEffect="slide"*/}
                {/*hideEffect="slide"*/}
                {/*showDelay={200} hideDelay={100} position="bottomLeft"*/}
                {/*targetPosition="topRight" showEffectLength={200}*/}
                {/*hideEffectLength={200} styleClass="icePnlTlTip">*/}
                {/*<span className="iceOutTxt"> Some imaginary TAC text. </span>*/}
                {/*</ace:tooltip>*/}
              </HPanelGroup>

              <HCommandButton value="Cancel"
                              action={this.props.cancel}
                              id="cancelBookingButton"
                              styleClass="iceCmdBtn btnOption"/>
              <HCommandButton value="Back"
                              immediate={true}
                              action={this.props.back}
                              styleClass="iceCmdBtn btnOption"/>
              <HCommandButton value="Finish"
                              id="finishButton"
                              action={this.confirmBooking}
                              styleClass="iceCmdBtn btnOption"/>

              <AceDialog id="infoPopup" header="Information"
                         visible={this.state.showInfo} closable={false}
                         modal={true}
                         draggable={false} resizable={false} showEffect="fade"
                         hideEffect="fade" styleClass="popup" showHeader={true}>
                <div className="contentLevelContainer">
                  <HPanelGroup layout="block" styleClass="inputFieldGroup">
                    <div className="inputFieldGroup center">
                      <span className="iceOutTxt inputFieldLabel">When clicking OK, you're booking the flight binding</span>
                    </div>
                    <div className="inputFieldGroup center">
                      <IceCommandButton value="OK" id="as_info_ok"
                                        action={this.finishBooking}
                                        immediate={true}
                                        partialSubmit={true}
                                        styleClass="btnOption"/>
                    </div>
                  </HPanelGroup>
                </div>
              </AceDialog>
            </HForm>
          </React.Fragment>
      );
    } else {
      return <BookingSuccess finish={this.props.cancel}/>;
    }
  }
}

// src/main/webapp/angular/app/components/pages/booking-details/booking-details.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'booking-details',
  templateUrl: './booking-details.component.html',
  styleUrls: ['./booking-details.component.css'],
})
export class BookingDetailsComponent {

  constructor() {
  }
}

<h-body>
    <app-base-template>
        <ui-define name="content">
            <h2>Booking Overview</h2>
            <h-form id="bookingDetails">
                <!-- show all entered data -->
                <cc-flight-details [headline]="true" [standalone]="false"
                                   [flight]="selectedFlight"></cc-flight-details>

                <h-panel-group layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <div class="inputFieldGroup">
                        <span class="iceOutTxt headerLabel">Basic Data</span>
                    </div>
                    <h-panel-group layout="block">
                        <div class="clear" style="height: 6px;"></div>
                        <div class="inputFieldGroup minindented">
                        <span class="iceOutTxt kdInputFieldLabel"
                              style="width: 200px;">Passenger Count:</span>
                            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                           [value]="passengerCount"></h-output-text>
                            <span class="iceOutTxt kdInputFieldLabel"
                                  style="width: 200px;">Flight Costs:</span>
                            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                           [value]="flightCosts">
                                <f-convert-number pattern="##,##" [groupingUsed]="true"
                                                  locale="de-DE"></f-convert-number>
                            </h-output-text>
                            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                           [rendered]="travelInsurance"
                                           value="Travel Insurance"
                            ></h-output-text>
                        </div>
                    </h-panel-group>
                </h-panel-group>
                <h-panel-group layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <div class="inputFieldGroup">
                        <span class="iceOutTxt headerLabel">Passenger Data</span>
                    </div>
                    <ui-repeat [value]="passengers" var="passenger">
                        <ng-template let-passenger>
                            <h-panel-group layout="block">
                                <div class="clear" style="height: 6px;"></div>
                                <div class="inputFieldGroup minindented">
                                    <c-choose>
                                        <!-- if other country -->
                                        <c-when [test]="selectedFlight.foreignTravel()">
                                            <!-- passport -->
                                            <span class="iceOutTxt kdInputFieldLabel"
                                                  style="width: 200px;">Passenger Passport:</span>
                                            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                           [value]="passenger.passportNumber"></h-output-text>
                                        </c-when>
                                        <c-otherwise>
                                            <!-- id card -->
                                            <span class="iceOutTxt kdInputFieldLabel"
                                                  style="width: 200px;">Passenger Id Card:</span>
                                            <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                           [value]="passenger.idCardNumber"></h-output-text>
                                        </c-otherwise>
                                    </c-choose>
                                    <span class="iceOutTxt kdInputFieldLabel"
                                          style="width: 200px;">Passenger Firstname:</span>
                                    <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                   [value]="passenger.firstName"></h-output-text>
                                    <span class="iceOutTxt kdInputFieldLabel"
                                          style="width: 200px;">Passenger Lastname:</span>
                                    <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                   [value]="passenger.lastName"></h-output-text>
                                    <span class="iceOutTxt kdInputFieldLabel"
                                          style="width: 200px;">Passenger Birthdate:</span>
                                    <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                   [value]="passenger.birthDay"
                                                   [converter]="shortDateConverter"></h-output-text>
                                    <span class="iceOutTxt kdInputFieldLabel"
                                          style="width: 200px;">Passenger # Luggage:</span>
                                    <h-output-text styleClass="iceOutTxt kdInputFieldLabel"
                                                   [value]="passenger.luggageCount"></h-output-text>
                                </div>
                            </h-panel-group>
                        </ng-template>
                    </ui-repeat>
                </h-panel-group>

                <h-panel-group layout="block"
                               styleClass="contentLevelContainer blockArea">
                    <h-panel-group id="tacDiv">
                        <ice-select-boolean-checkbox id="tacCheckbox" [(ngModel)]="tac"
                                                     [validator]="validateTac"></ice-select-boolean-checkbox>
                        <h-output-label id="tacCheckboxLabel" for="tacCheckbox">Accept TAC
                        </h-output-label>

                        <h-message styleClass="iceMsgError inputFieldLabel"
                                   for="tacCheckbox" id="tacErrorMessage"></h-message>
                    </h-panel-group>
                    <ace-tooltip id="tacTooltip" for="tacDiv"
                                 [speechBubble]="false" showEffect="slide" hideEffect="slide"
                                 [showDelay]="200" [hideDelay]="100" position="bottomLeft"
                                 targetPosition="topRight" [showEffectLength]="200"
                                 [hideEffectLength]="200" styleClass="icePnlTlTip">
                        <span class="iceOutTxt"> Some imaginary TAC text. </span>
                    </ace-tooltip>
                </h-panel-group>

                <h-command-button value="Cancel"
                                  (action)="cancelBooking()"
                                  [immediate]="true"
                                  id="cancelBookingButton"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>
                <h-command-button value="Back"
                                  [immediate]="true"
                                  (action)="back()"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>
                <h-command-button value="Finish"
                                  id="finishButton"
                                  (action)="confirmBooking()"
                                  styleClass="iceCmdBtn btnOption"></h-command-button>

                <ace-dialog id="infoPopup" header="Information"
                            [visible]="showInfo" [closable]="false" [modal]="true"
                            [draggable]="false" [resizable]="false" showEffect="fade"
                            hideEffect="fade" styleClass="popup" [showHeader]="true">
                    <div class="contentLevelContainer">
                        <h-panel-group layout="block" styleClass="inputFieldGroup">
                            <div class="inputFieldGroup center">
                                <span class="iceOutTxt inputFieldLabel">When clicking OK, you're booking the flight binding</span>
                            </div>
                            <div class="inputFieldGroup center">
                                <ice-command-button value="OK" id="as_info_ok"
                                                    (action)="finishBooking()"
                                                    [immediate]="true"
                                                    [partialSubmit]="true"
                                                    styleClass="btnOption"></ice-command-button>
                            </div>
                        </h-panel-group>
                    </div>
                </ace-dialog>
            </h-form>
        </ui-define>
    </app-base-template>
</h-body>
